import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFile } from "node:fs/promises";
import { FIRST_RUN_RESPONSIVE_LAYOUTS,deriveResponsiveEvidence } from "../src/responsiveImageProjection.js";
const require=createRequire(import.meta.url);const{chromium}=require("playwright");const styles=await readFile(new URL("../src/styles.css",import.meta.url),"utf8");
const relation={x:430,y:560,width:2980,height:1140},semanticTarget={x:280,y:480,width:3280,height:1400};
const browser=await chromium.launch({headless:true,executablePath:"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",args:["--disable-gpu"]});
try{for(const[id,viewport]of Object.entries(FIRST_RUN_RESPONSIVE_LAYOUTS)){const context=await browser.newContext({viewport,forcedColors:id==="retained320x240"?"active":"none",reducedMotion:id==="effective200"?"reduce":"no-preference"});const page=await context.newPage();const evidence=deriveResponsiveEvidence({viewport,relation,semanticTarget});const width=`max(${semanticTarget.width/38.4}%, 44px)`,height=`max(${semanticTarget.height/21.6}%, 44px)`,centerX=(semanticTarget.x+semanticTarget.width/2)/38.4,centerY=(semanticTarget.y+semanticTarget.height/2)/21.6;await page.setContent(`<style>${styles}</style><div class="canonical-game-host"><div class="crt-stage-anchor"><div class="crt-shell"><div class="canonical-game-frame"><main class="game-shell adventure-screen" data-scene="ruins"><section class="scene-frame"><div class="scene-world-content"><img class="scene-art blind-camera-well-art" alt="fixture"><button class="hotspot hotspot-secondary" style="--hotspot-left:clamp(0px,calc(${centerX}% - ${width}/2),calc(100% - ${width}));--hotspot-top:clamp(0px,calc(${centerY}% - ${height}/2),calc(100% - ${height}));--hotspot-width:${width};--hotspot-height:${height};--hotspot-narrow-left:clamp(0px,calc(${centerX}% - ${width}/2),calc(100% - ${width}));--hotspot-narrow-top:clamp(0px,calc(${centerY}% - ${height}/2),calc(100% - ${height}));--hotspot-narrow-width:${width};--hotspot-narrow-height:${height}"><span>USE fixture</span></button></div></section><section class="command-panel"></section></main></div></div></div></div>`);const actual=await page.evaluate(()=>{const world=document.querySelector(".scene-frame").getBoundingClientRect(),image=document.querySelector("img"),ib=image.getBoundingClientRect(),button=document.querySelector("button");button.focus();const b=button.getBoundingClientRect(),s=getComputedStyle(button);return{world,ib,b,fit:getComputedStyle(image).objectFit,pos:getComputedStyle(image).objectPosition,focus:document.activeElement===button,outline:parseFloat(s.outlineWidth)||0,sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth};});assert.ok(evidence.relation.retainedArea>=.95);assert.ok(Math.abs(actual.ib.width-actual.world.width)<1.1&&Math.abs(actual.ib.height-actual.world.height)<1.1);assert.equal(actual.fit,"cover");assert.equal(actual.pos,"50% 50%");assert.ok(actual.b.width>=44&&actual.b.height>=44);assert.ok(actual.b.x>=actual.world.x-1&&actual.b.y>=actual.world.y-1&&actual.b.right<=actual.world.right+1&&actual.b.bottom<=actual.world.bottom+1);assert.equal(actual.focus,true);assert.ok(actual.outline>=2);assert.equal(actual.sw,actual.cw);await context.close();}}finally{await browser.close();}
console.log(`BLIND_CAMERA_WELL_RESPONSIVE_BROWSER_PASS|layouts=${Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS).length}|forcedColors=1|reducedMotion=1`);
