import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { BORROWED_LIGHT_WALL_COPY, BORROWED_LIGHT_WALL_PATH, BORROWED_LIGHT_WALL_PROVENANCE, BORROWED_LIGHT_WALL_REGISTRY, BORROWED_LIGHT_WALL_SOURCE_URL, deriveBorrowedLightWallResponsiveEvidence, deriveBorrowedLightWallState, getBorrowedLightWallHotspot, isBorrowedLightWallMeasurementPass, isBorrowedLightWallSourceIdentityPass, isLegacyHost11LessonLauncherVisible } from "../src/borrowedLightWall.js";
const source = { enabled: true, path: BORROWED_LIGHT_WALL_PATH, sha256: "a".repeat(64), byteLength: 12000000, width: 3840, height: 2160, format: "png", color: "opaque-srgb-8", attemptId: "H11-1" };
const provenance = { sha256: source.sha256, byteLength: source.byteLength, promptId: "HOST11-GEN-PROMPT-H11-1", promptBytes: 1301, promptSha256: "0e32cea1cbab100ee44ec2fd502cf1eaab0a97d029eb3504ae9bcad1c9949d92", cliSha256: "c2cdb05244ad9a3dcb8731988790ea6a06a59ab3c062c0f872b35f4ad7d20b05" };
function registry() { return { source, receivingWall: { x: 1050, y: 360, width: 1740, height: 1400, centerX: 1920, centerY: 1060 }, mineralFilm: { x: 1180, y: 480, width: 1480, height: 950 }, apertures: [{ x: 1350, y: 650, width: 180, height: 220 }, { x: 1820, y: 560, width: 200, height: 240 }, { x: 2290, y: 700, width: 180, height: 220 }], returnPaths: [{ x: 1320, y: 1000, width: 900, height: 100 }, { x: 1750, y: 1150, width: 900, height: 100 }], dryApron: { x: 900, y: 1500, width: 2040, height: 500 }, serviceThroat: { x: 2450, y: 1020, width: 250, height: 420 }, semanticTarget: { x: 850, y: 300, width: 2140, height: 1750 }, labelAnchor: { x: 880, y: 330, width: 2080, height: 1690, insetOuterCss: 3, insetTextCss: 5 }, protected: { host10: null, returnRoute: null, crown: null, host12: null } }; }
test("Host 11 selected source is identity-bound, measured, and content complete", () => { assert.equal(BORROWED_LIGHT_WALL_REGISTRY.source.enabled, true); assert.equal(BORROWED_LIGHT_WALL_SOURCE_URL, BORROWED_LIGHT_WALL_PATH); assert.equal(isBorrowedLightWallSourceIdentityPass(), true); assert.equal(isBorrowedLightWallMeasurementPass(), true); assert.ok(getBorrowedLightWallHotspot()); for (const value of Object.values(BORROWED_LIGHT_WALL_COPY)) assert.ok(value); assert.equal(BORROWED_LIGHT_WALL_PROVENANCE.sha256, BORROWED_LIGHT_WALL_REGISTRY.source.sha256); });
test("Host 11 accepts exact attempt domain and cap", () => { assert.equal(isBorrowedLightWallSourceIdentityPass(source, provenance), true); assert.equal(isBorrowedLightWallSourceIdentityPass({ ...source, attemptId: "H11-11" }, provenance), false); assert.equal(isBorrowedLightWallSourceIdentityPass({ ...source, byteLength: 30000001 }, provenance), false); });
test("Host 11 derives six layouts and target", () => { const selected = registry(); assert.equal(isBorrowedLightWallMeasurementPass(selected), true); assert.equal(Object.keys(deriveBorrowedLightWallResponsiveEvidence(selected)).length, 6); assert.ok(getBorrowedLightWallHotspot(selected)); });
test("Host 11 fails closed and retires generic launchers", () => { assert.equal(isLegacyHost11LessonLauncherVisible(), false); assert.equal(isLegacyHost11LessonLauncherVisible({ enabled: false }), true); assert.equal(isLegacyHost11LessonLauncherVisible(source), false); assert.equal(deriveBorrowedLightWallState({ predecessorComplete: true, registry: registry(), provenance, decodedImage: { complete: true, naturalWidth: 3840, naturalHeight: 2160 } }), "available"); });
test("App guards both Host 11 generic launchers", async () => { const app = await readFile(new URL("../src/App.jsx", import.meta.url), "utf8"); assert.match(app, /isLegacyHost11LessonLauncherVisible/); assert.equal((app.match(/legacyHost11LessonLauncherVisible && pendingAdvance/g) ?? []).length, 2); });
