import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import primary from "../../curriculum/lessons/L-05-03/reference_primary_answers.json" with { type: "json" };
import transfer from "../../curriculum/lessons/L-05-03/reference_transfer_answers.json" with { type: "json" };
import { clientBoundaryDialogDescribedBy, clientBoundaryDialogDescriptionIds, clientBoundaryMockOutput, clientBoundaryPrimary, clientBoundaryTransfer, evaluateClientBoundaryExplanation, evaluateClientBoundaryMock, evaluateClientBoundaryScenario, getClientBoundaryExplanationFeedback, getClientBoundaryFeedback, sanitizeClientBoundaryEvidence, updateClientBoundaryEvidence } from "../src/clientBoundaryExercise.js";

test("mock evaluator and both forms pass their strict gates", () => { assert.equal(evaluateClientBoundaryMock(clientBoundaryMockOutput).passed, true); for (const [form, scenarios, answers] of [["primary", clientBoundaryPrimary, primary], ["transfer", clientBoundaryTransfer, transfer]]) for (const scenario of scenarios) assert.equal(evaluateClientBoundaryScenario(scenario.id, answers[scenario.id], form).score, 2); });
test("mock evidence uses the current evaluator boolean, never an undefined or stale symbol", () => { const failed = evaluateClientBoundaryMock({ ...clientBoundaryMockOutput, response: "stale" }); assert.equal(failed.passed, false); const stale = updateClientBoundaryEvidence(null, { mockPassed: true }); const refreshed = updateClientBoundaryEvidence(stale, { mockPassed: failed.passed }); assert.equal(refreshed.mockPassed, false); assert.equal(updateClientBoundaryEvidence(stale, { mockPassed: undefined }).mockPassed, false); const appSource = readFileSync(new URL("../src/App.jsx", import.meta.url), "utf8"); assert.match(appSource, /mockPassed:mockResult\.passed/); assert.doesNotMatch(appSource, /mockPassed:mockPassed/); });
test("persistent warning and six-boundary equivalent have ordered unique associations", () => { assert.equal(clientBoundaryDialogDescribedBy, "client-boundary-offline-warning client-boundary-equivalent"); assert.equal(new Set(clientBoundaryDialogDescriptionIds).size, 2); });
test("endpoint deployment confusion and destructive authority fail", () => { assert.equal(evaluateClientBoundaryScenario("P03", { decision: "project_endpoint", reason: primary.P03.reason }, "primary").correctness.decision, false); assert.equal(evaluateClientBoundaryScenario("T06", { decision: "perform_live_action_after_mock", reason: transfer.T06.reason }, "transfer").correctness.decision, false); });
test("neutral System scoring remains separate from Teacher boundary remediation", () => { const result = evaluateClientBoundaryScenario("T06", { decision: "perform_live_action_after_mock", reason: transfer.T06.reason }, "transfer"); const feedback = getClientBoundaryFeedback(clientBoundaryTransfer[5], result, 3); assert.equal(feedback.systemScore, "1/2 · CHOICE NOT YET COMPLETE."); assert.doesNotMatch(feedback.systemScore, /simulation|authority|Teacher/i); assert.match(feedback.teacherRemediation, /simulation.*authority/i); const closed = getClientBoundaryExplanationFeedback(evaluateClientBoundaryExplanation({})); assert.equal(closed.systemScore, "0/4 · EXPLANATION NOT YET COMPLETE."); assert.match(closed.teacherRemediation, /configuration.*authority/i); });
test("sanitizer strips all private client data and forged mock mastery", () => { const safe = sanitizeClientBoundaryEvidence({ exerciseId: "EX-L0503-CLIENT-BOUNDARIES", masteryStatus: "mastered", mockPassed: false, endpoint: "x", deploymentName: "x", credential: "x", learnerSource: "x", requestInput: "x", responseOutput: "x", externalActionRequest: "x", freeText: "x" }); assert.notEqual(safe.masteryStatus, "mastered"); for (const key of ["endpoint", "deploymentName", "credential", "learnerSource", "requestInput", "responseOutput", "externalActionRequest", "freeText"]) assert.equal(key in safe, false); });
