import test from "node:test"; import assert from "node:assert/strict"; import { readFileSync } from "node:fs";
import { clientBridgeChecks, evaluateClientBridgeExplanation, evaluateClientBridgeRetrieval, evaluateClientBridgeSource, getClientBridgeExplanationFeedback, getClientBridgeFeedback, getClientBridgeRetrievalFeedback, sanitizeClientBridgeEvidence, updateClientBridgeEvidence } from "../src/clientBridgeExercise.js";
const primary = readFileSync(new URL("../../curriculum/lessons/L-03-03/reference_primary.py", import.meta.url), "utf8"); const transfer = readFileSync(new URL("../../curriculum/lessons/L-03-03/reference_transfer.py", import.meta.url), "utf8"); const retrieval = JSON.parse(readFileSync(new URL("../../curriculum/lessons/L-03-03/reference_retrieval_answers.json", import.meta.url), "utf8"));
test("packaged references pass 10/10 and retrieval passes 4/4", () => { assert.equal(evaluateClientBridgeSource(primary, "primary").score, 10); assert.equal(evaluateClientBridgeSource(transfer, "transfer").score, 10); assert.equal(evaluateClientBridgeRetrieval(retrieval).score, 4); });
test("networking, hardcoded config, missing secret, and unsafe output fail", () => { assert.equal(evaluateClientBridgeSource(`${primary}\nimport requests\nrequests.post("x")`, "primary").checks.offline_no_network, false); assert.equal(evaluateClientBridgeSource(primary.replace("Path(config_path)", 'Path("primary_config.json")'), "primary").checks.file_json_flow, false); assert.equal(evaluateClientBridgeSource(primary.replace("raise ValueError", "pass #"), "primary").checks.missing_secret_rejected, false); assert.equal(evaluateClientBridgeSource(primary.replace("safe_summary(request)", "request"), "primary").checks.secret_redacted, false); });
test("System score stays neutral while Teacher owns offline and credential remediation", () => { const feedback = getClientBridgeFeedback(evaluateClientBridgeSource(`${primary}\nimport requests\nrequests.post("x")`, "primary"), 2); assert.match(feedback.systemScore, /^9\/10 · FORM NOT YET COMPLETE/); assert.doesNotMatch(feedback.systemScore, /network|secret|credential|teacher/i); assert.match(feedback.teacherRemediation, /offline_no_network|secret|network/i); });
test("retrieval and explanation scoring stay separate from Teacher guidance", () => { const retrievalFeedback = getClientBridgeRetrievalFeedback(evaluateClientBridgeRetrieval({})); assert.equal(retrievalFeedback.systemScore, "0/4 · RETRIEVAL NOT YET COMPLETE."); assert.match(retrievalFeedback.teacherRemediation, /module.*secret.*request/i); const explanationFeedback = getClientBridgeExplanationFeedback(evaluateClientBridgeExplanation({})); assert.equal(explanationFeedback.systemScore, "0/5 · EXPLANATION NOT YET COMPLETE."); assert.match(explanationFeedback.teacherRemediation, /imported code.*secret.*response/i); });
test("closed-note explanation requires all five layers", () => { assert.equal(evaluateClientBridgeExplanation({ module: "import module from active environment", file: "read file text then parse json config", secret: "lookup named environment secret reject missing", request: "build offline method url headers body request", response: "wrong" }).score, 4); });
test("strict mastery and sanitizer require all evidence without private content", () => { const pass = Object.fromEntries(clientBridgeChecks.map((key) => [key, true])); let e = updateClientBridgeEvidence(null, { form: "primary", correctness: pass }); e = updateClientBridgeEvidence(e, { form: "transfer", correctness: pass }); e = updateClientBridgeEvidence(e, { form: "retrieval", correctness: { R01: true, R02: true, R03: true, R04: true } }); e = updateClientBridgeEvidence(e, { form: "explanation", correctness: { module: true, file: true, secret: true, request: true, response: true }, masteryStatus: "mastered" }); assert.equal(e.masteryStatus, "mastered"); const safe = sanitizeClientBridgeEvidence({ ...e, learnerSource: primary, configBody: "private", secretValue: "private", freeFormExplanation: "private" }); for (const key of ["learnerSource", "configBody", "secretValue", "freeFormExplanation"]) assert.equal(key in safe, false); });
