import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { DROWNED_SWITCHYARD_COPY, DROWNED_SWITCHYARD_PATH, DROWNED_SWITCHYARD_REGISTRY, deriveDrownedSwitchyardResponsiveEvidence, deriveDrownedSwitchyardState, getDrownedSwitchyardHotspot, isDrownedSwitchyardMeasurementPass, isDrownedSwitchyardSourceIdentityPass, isLegacyHost12LessonLauncherVisible } from "../src/drownedSwitchyard.js";
const source = { enabled: true, path: DROWNED_SWITCHYARD_PATH, sha256: "a".repeat(64), byteLength: 12000000, width: 3840, height: 2160, format: "png", color: "opaque-srgb-8", attemptId: "H12-1" };
const provenance = { sha256: source.sha256, byteLength: source.byteLength, promptId: "HOST12-GEN-PROMPT-H12-1", promptBytes: 1285, promptSha256: "a5b2af07451e0a562986a8b59314d9acda57979615c9ac3d4034fade4dd9411d", cliSha256: "c2cdb05244ad9a3dcb8731988790ea6a06a59ab3c062c0f872b35f4ad7d20b05" };
function registry() { return { source, upperCrown: { x: 1250, y: 420, width: 1340, height: 1260, centerX: 1920, centerY: 1050 }, dryApproach: { x: 900, y: 1500, width: 2040, height: 500 }, bypassSeams: [{ x: 1450, y: 1000, width: 100, height: 420 }, { x: 1850, y: 920, width: 100, height: 500 }, { x: 2250, y: 1000, width: 100, height: 420 }], sealedChambers: [{ x: 1550, y: 620, width: 260, height: 240 }, { x: 2050, y: 620, width: 260, height: 240 }], drownedReturns: [{ x: 1120, y: 1300, width: 800, height: 250 }, { x: 1920, y: 1300, width: 800, height: 250 }], waterBoundary: { x: 700, y: 1250, width: 2440, height: 500 }, semanticTarget: { x: 1050, y: 350, width: 1740, height: 1500 }, labelAnchor: { x: 1080, y: 380, width: 1680, height: 1440, insetOuterCss: 3, insetTextCss: 5 }, protected: { host11: null, returnRoute: null, host13: null, witness: null } }; }
test("Host 12 selected source is identity-bound, measured, and content complete", () => { assert.equal(DROWNED_SWITCHYARD_REGISTRY.source.enabled, true); assert.equal(isDrownedSwitchyardSourceIdentityPass(), true); assert.equal(isDrownedSwitchyardMeasurementPass(), true); assert.ok(getDrownedSwitchyardHotspot()); for (const value of Object.values(DROWNED_SWITCHYARD_COPY)) assert.ok(value); });
test("Host 12 accepts only its exact attempt domain and cap", () => { assert.equal(isDrownedSwitchyardSourceIdentityPass(source, provenance), true); assert.equal(isDrownedSwitchyardSourceIdentityPass({ ...source, attemptId: "H12-10" }, provenance), false); assert.equal(isDrownedSwitchyardSourceIdentityPass({ ...source, byteLength: 30000001 }, provenance), false); });
test("Host 12 requires complete physical geometry and derives six layouts", () => { const selected = registry(); assert.equal(isDrownedSwitchyardMeasurementPass(selected), true); assert.equal(Object.keys(deriveDrownedSwitchyardResponsiveEvidence(selected)).length, 6); assert.ok(getDrownedSwitchyardHotspot(selected)); assert.equal(isDrownedSwitchyardMeasurementPass({ ...selected, sealedChambers: selected.sealedChambers.slice(0, 1) }), false); });
test("Host 12 fails closed and retires only its generic launchers", () => { assert.equal(isLegacyHost12LessonLauncherVisible(), false); assert.equal(isLegacyHost12LessonLauncherVisible({ enabled: false }), true); assert.equal(isLegacyHost12LessonLauncherVisible(source), false); assert.equal(deriveDrownedSwitchyardState({ predecessorComplete: true, registry: registry(), provenance, decodedImage: { complete: true, naturalWidth: 3840, naturalHeight: 2160 } }), "available"); });
test("App guards SDK and Single Agent but not Client Boundaries", async () => { const app = await readFile(new URL("../src/App.jsx", import.meta.url), "utf8"); assert.match(app, /isLegacyHost12LessonLauncherVisible/); assert.equal((app.match(/legacyHost12LessonLauncherVisible && pendingAdvance/g) ?? []).length, 2); assert.match(app, /pendingAdvance&&scene\.id==="ruins"&&promptEvidence\?\.masteryStatus==="mastered"&&clientBoundaryEvidence/); });
test("clean-start E2E follows the selected Host 12 boundary after both owned lessons", async () => { const e2e = await readFile(new URL("../../playtest/e2e-playthrough.mjs", import.meta.url), "utf8"); const selectedBoundaryUses = e2e.match(/page\.locator\('\[data-hotspot-id="drowned-switchyard"\]'\)/g) ?? []; assert.ok(selectedBoundaryUses.length >= 3); assert.doesNotMatch(e2e, /const clientBoundaryContinue=page\.getByRole\("button",\{name:"Start SDK Route Chooser"/); assert.doesNotMatch(e2e, /const singleAgentAfterSdk=page\.getByRole\("button",\{name:"Start Single Agent"/); assert.doesNotMatch(e2e, /const restoredClientBoundaryContinue = page\.getByRole\("button", \{ name: "Start Single Agent"/); });
