import test from "node:test";
import assert from "node:assert/strict";
import answers from "../../curriculum/readiness/SIM-03/reference_answers.json" with {type:"json"};
import entry from "../../curriculum/readiness/SIM-03/reference_entry_evidence.json" with {type:"json"};
import {deriveFinalConfidenceResume,evaluateFinalConfidenceEntryGate,evaluateFinalConfidenceItem,finalConfidenceItems,getFinalConfidenceFeedback,sanitizeFinalConfidenceEvidence,updateFinalConfidenceEvidence} from "../src/finalConfidenceExercise.js";

const runtimeEntry={l0603ReadinessState:entry.l0603_readiness_state,cum01TransferScore:entry.cum01_transfer_score,sim01Score:entry.sim01_score,sim02Score:entry.sim02_score,priorSimulationSeparationHours:entry.sim01_sim02_separation_hours,openCriticalMisconceptions:entry.open_critical_misconceptions,highConfidenceMissesRetested:entry.high_confidence_misses_retested,officialSourcesReverifiedOn:entry.official_sources_reverified_on,attemptedOn:entry.attempted_on};

test("entry gate matches the Teacher package and rejects every weakened prerequisite",()=>{assert.equal(evaluateFinalConfidenceEntryGate(runtimeEntry).ready,true);for(const [key,value] of Object.entries({l0603ReadinessState:"not_ready",cum01TransferScore:15,sim01Score:23,sim02Score:23,priorSimulationSeparationHours:47,openCriticalMisconceptions:1,highConfidenceMissesRetested:false,officialSourcesReverifiedOn:"2026-07-05"})){assert.equal(evaluateFinalConfidenceEntryGate({...runtimeEntry,[key]:value}).ready,false,key);}});
test("reference answers pass strict 24/24 one scenario at a time",()=>{assert.equal(finalConfidenceItems.reduce((score,item)=>score+evaluateFinalConfidenceItem(item.id,answers[item.id]).score,0),24);assert.equal(new Set(finalConfidenceItems.flatMap(item=>item.objective_ids)).size,15);});
test("a miss gets targeted Teacher remediation and cannot advance correctness",()=>{const item=finalConfidenceItems[6],result=evaluateFinalConfidenceItem(item.id,{decision:"wrong",reason:"wrong"}),feedback=getFinalConfidenceFeedback(item,result);assert.equal(result.passed,false);assert.match(feedback.teacherRemediation,/AI901-D2-O2.*AI901-D2-O3.*blank choices.*Confidence does not repair/i);});
test("mastery cannot be forged without gate and all 24 dimensions",()=>{const forged=sanitizeFinalConfidenceEvidence({exerciseId:"EX-SIM03-FINAL-CONFIDENCE",masteryStatus:"mastered",entryEvidence:{...runtimeEntry,sim02Score:0},dimensionCorrectness:Object.fromEntries(finalConfidenceItems.map(item=>[item.id,{decision:true,reason:true}]))});assert.equal(forged.masteryStatus,"entry_gate_incomplete");let evidence=updateFinalConfidenceEvidence(null,{entryEvidence:runtimeEntry,masteryStatus:"in_progress"});for(const item of finalConfidenceItems){const result=evaluateFinalConfidenceItem(item.id,answers[item.id]);evidence=updateFinalConfidenceEvidence(evidence,{itemId:item.id,correctness:result.correctness,incrementAttempt:true});}evidence=updateFinalConfidenceEvidence(evidence,{confidence:"high",masteryStatus:"mastered"});assert.equal(evidence.masteryStatus,"mastered");assert.deepEqual(deriveFinalConfidenceResume(evidence),{index:11,complete:true,completedCount:12,elapsedSeconds:0,timingEnabled:false});});
test("privacy allowlist strips working answers and prohibited authority data",()=>{const safe=sanitizeFinalConfidenceEvidence({exerciseId:"EX-SIM03-FINAL-CONFIDENCE",entryEvidence:runtimeEntry,response:{decision:"private",reason:"private"},examItemText:"x",privateNote:"x",credential:"x",endpoint:"x",resourceName:"x",deploymentName:"x",payload:"x",serviceResponse:"x",externalActionRequest:"x",masteryStatus:"in_progress"});for(const key of ["response","examItemText","privateNote","credential","endpoint","resourceName","deploymentName","payload","serviceResponse","externalActionRequest"])assert.equal(key in safe,false);assert.equal(JSON.stringify(safe).includes("private"),false);});
test("App exposes the optional gate only after SIM-01 and renders one gated item at a time",async()=>{const{readFileSync}=await import("node:fs"),source=readFileSync(new URL("../src/App.jsx",import.meta.url),"utf8"),css=readFileSync(new URL("../src/styles.css",import.meta.url),"utf8"),manifest=JSON.parse(readFileSync(new URL("../public/question-manifest.json",import.meta.url),"utf8"));assert.match(source,/mixedSimulationEvidence\?\.masteryStatus==="mastered"&&finalConfidenceEvidence\?\.masteryStatus!=="mastered"/);assert.match(source,/phase:gate\.ready\?"items":"gate"/);assert.match(source,/finalConfidenceItems\[finalConfidenceSession\.index\]/);assert.match(source,/Confidence \(separate from correctness\)/);assert.match(source,/Retry with blank choices/);assert.match(source,/No result, confidence, or saved evidence authorizes credentials, Azure mutation/);assert.match(css,/\.final-confidence-gate \.model-choice-fields \{ grid-template-columns: repeat\(3/);assert.ok(manifest.questions.some(question=>question.exercise_id==="EX-SIM03-FINAL-CONFIDENCE"));});
