import test from "node:test";
import assert from "node:assert/strict";
import answers from "../../curriculum/readiness/SIM-03/reference_answers.json" with {type:"json"};
import entry from "../../curriculum/readiness/SIM-03/reference_entry_evidence.json" with {type:"json"};
import {deriveFinalConfidenceResume,evaluateFinalConfidenceEntryGate,evaluateFinalConfidenceItem,finalConfidenceItems,getFinalConfidenceFeedback,sanitizeFinalConfidenceEvidence,updateFinalConfidenceEvidence} from "../src/finalConfidenceExercise.js";

const runtimeEntry={l0603ReadinessState:entry.l0603_readiness_state,cum01TransferScore:entry.cum01_transfer_score,sim01Score:entry.sim01_score,sim02Score:entry.sim02_score,priorSimulationSeparationHours:entry.sim01_sim02_separation_hours,openCriticalMisconceptions:entry.open_critical_misconceptions,highConfidenceMissesRetested:entry.high_confidence_misses_retested,officialSourcesReverifiedOn:entry.official_sources_reverified_on,attemptedOn:entry.attempted_on};

test("entry gate matches the Teacher package and rejects every weakened prerequisite",()=>{assert.equal(evaluateFinalConfidenceEntryGate(runtimeEntry).ready,true);for(const [key,value] of Object.entries({l0603ReadinessState:"not_ready",cum01TransferScore:15,sim01Score:23,sim02Score:23,priorSimulationSeparationHours:47,openCriticalMisconceptions:1,highConfidenceMissesRetested:false,officialSourcesReverifiedOn:"2026-07-05"})){assert.equal(evaluateFinalConfidenceEntryGate({...runtimeEntry,[key]:value}).ready,false,key);}});
test("reference answers pass strict 24/24 one scenario at a time",()=>{assert.equal(finalConfidenceItems.reduce((score,item)=>score+evaluateFinalConfidenceItem(item.id,answers[item.id]).score,0),24);assert.equal(new Set(finalConfidenceItems.flatMap(item=>item.objective_ids)).size,15);});
test("a miss gets targeted Teacher remediation and cannot advance correctness",()=>{const item=finalConfidenceItems[6],result=evaluateFinalConfidenceItem(item.id,{decision:"wrong",reason:"wrong"}),feedback=getFinalConfidenceFeedback(item,result);assert.equal(result.passed,false);assert.match(feedback.teacherRemediation,/AI901-D2-O2.*AI901-D2-O3.*blank choices.*Confidence does not repair/i);});
test("mastery cannot be forged without gate and all 24 dimensions",()=>{const forged=sanitizeFinalConfidenceEvidence({exerciseId:"EX-SIM03-FINAL-CONFIDENCE",masteryStatus:"mastered",entryEvidence:{...runtimeEntry,sim02Score:0},dimensionCorrectness:Object.fromEntries(finalConfidenceItems.map(item=>[item.id,{decision:true,reason:true}]))});assert.equal(forged.masteryStatus,"entry_gate_incomplete");let evidence=updateFinalConfidenceEvidence(null,{entryEvidence:runtimeEntry,masteryStatus:"in_progress"});for(const item of finalConfidenceItems){const result=evaluateFinalConfidenceItem(item.id,answers[item.id]);evidence=updateFinalConfidenceEvidence(evidence,{itemId:item.id,correctness:result.correctness,incrementAttempt:true});}evidence=updateFinalConfidenceEvidence(evidence,{confidence:"high",masteryStatus:"mastered"});assert.equal(evidence.masteryStatus,"mastered");assert.deepEqual(deriveFinalConfidenceResume(evidence),{index:11,complete:true,completedCount:12,elapsedSeconds:0,timingEnabled:false});});
test("privacy allowlist strips working answers and prohibited authority data",()=>{const safe=sanitizeFinalConfidenceEvidence({exerciseId:"EX-SIM03-FINAL-CONFIDENCE",entryEvidence:runtimeEntry,response:{decision:"private",reason:"private"},examItemText:"x",privateNote:"x",credential:"x",endpoint:"x",resourceName:"x",deploymentName:"x",payload:"x",serviceResponse:"x",externalActionRequest:"x",masteryStatus:"in_progress"});for(const key of ["response","examItemText","privateNote","credential","endpoint","resourceName","deploymentName","payload","serviceResponse","externalActionRequest"])assert.equal(key in safe,false);assert.equal(JSON.stringify(safe).includes("private"),false);});
test("App exposes the optional gate only after SIM-01 and renders one gated item at a time",async()=>{const{readFileSync}=await import("node:fs"),source=readFileSync(new URL("../src/App.jsx",import.meta.url),"utf8"),css=readFileSync(new URL("../src/styles.css",import.meta.url),"utf8"),manifest=JSON.parse(readFileSync(new URL("../public/question-manifest.json",import.meta.url),"utf8"));assert.match(source,/const showFinalConfidenceAction = pendingAdvance[\s\S]*?scene\.id === "ruins"[\s\S]*?mixedSimulationEvidence\?\.masteryStatus === "mastered"[\s\S]*?finalConfidenceEvidence\?\.masteryStatus !== "mastered"/);assert.match(source,/phase:gate\.ready\?"items":"gate"/);assert.match(source,/finalConfidenceItems\[finalConfidenceSession\.index\]/);assert.match(source,/Confidence \(separate from correctness\)/);assert.match(source,/Retry with blank choices/);assert.match(source,/No result, confidence, or saved evidence authorizes credentials, Azure mutation/);assert.match(css,/\.final-confidence-gate \.model-choice-fields \{[\s\S]*?grid-template-columns: repeat\(3/);assert.ok(manifest.questions.some(question=>question.exercise_id==="EX-SIM03-FINAL-CONFIDENCE"));});
test("SIM-03 keeps one scroll path, whole-pixel gate controls, and contained optional actions",async()=>{const{readFileSync}=await import("node:fs"),css=readFileSync(new URL("../src/styles.css",import.meta.url),"utf8");assert.match(css,/data-terminal-exercise="EX-SIM03-FINAL-CONFIDENCE"\] \{ overflow: hidden; \}/);assert.match(css,/\.final-confidence-workspace \{[\s\S]*?display: block;[\s\S]*?overflow: auto;/);assert.match(css,/\.final-confidence-gate \.model-choice-fields \{[\s\S]*?repeat\(3, minmax\(0, 1fr\)\);[\s\S]*?gap: 4px;/);assert.match(css,/\.final-confidence-gate \.model-choice-fields label \{[\s\S]*?padding: 4px;[\s\S]*?border-radius: 0;[\s\S]*?font-size: 8px;[\s\S]*?line-height: 10px;[\s\S]*?overflow-wrap: anywhere;/);assert.match(css,/\.final-confidence-gate \.model-choice-fields select,[\s\S]*?min-height: 24px;[\s\S]*?padding: 3px 4px;[\s\S]*?box-shadow: none;[\s\S]*?font-size: 8px;[\s\S]*?line-height: 10px;/);assert.match(css,/data-canonical-layout="narrow"\] \.final-confidence-gate \.model-choice-fields \{[\s\S]*?grid-template-columns: 1fr;[\s\S]*?gap: 4px;/);assert.match(css,/\.canonical-game-frame \.dialogue-actions \.continue-action \{[\s\S]*?min-height: 24px;[\s\S]*?border-radius: 0;[\s\S]*?font-size: 8px;[\s\S]*?line-height: 10px;/);assert.match(css,/data-canonical-layout="narrow"\] \.dialogue-actions \.continue-action\.optional-practice-action \{[\s\S]*?flex: 3;[\s\S]*?white-space: normal;[\s\S]*?overflow-wrap: anywhere;/);});

test("SIM-03 exposes field-specific entry errors and deterministic keyboard transitions",async()=>{
  const {readFileSync}=await import("node:fs");
  const source=readFileSync(new URL("../src/App.jsx",import.meta.url),"utf8");
  const css=readFileSync(new URL("../src/styles.css",import.meta.url),"utf8");
  for(const check of ["l0603Readiness","cum01Transfer","sim01","sim02","spacing","criticalMisconceptions","highConfidenceRetest","sourceFreshness"]){
    assert.match(source,new RegExp(`final-confidence-entry-\\$\\{check\\}-feedback|final-confidence-entry-${check}-feedback|finalConfidenceEntryA11y\\(finalConfidenceSession\\.entryGate,\\"${check}\\"\\)`),check);
  }
  assert.match(source,/aria-atomic="true"/);
  assert.match(source,/form\.querySelector\('\[aria-invalid="true"\]'\)/);
  assert.match(source,/finalConfidenceTimerRef\.current/);
  assert.match(source,/finalConfidenceFirstSelectRef\.current\?\.focus/);
  assert.match(source,/finalConfidenceItemHeadingRef\.current\?\.focus/);
  assert.match(source,/finalConfidenceSummaryHeadingRef\.current\?\.focus/);
  assert.match(source,/disabled=\{!finalConfidenceEvidence\?\.confidence\}/);
  assert.match(source,/data-final-confidence-action=\{showFinalConfidenceAction \? "true" : undefined\}/);
  assert.match(source,/showFinalConfidenceAction&&<button className="continue-action optional-practice-action"/);
  assert.doesNotMatch(source,/showFinalConfidenceAction&&<button ref=/);
  assert.match(source,/focusContinueAfterMixedSimulationRef\.current=false;continueButtonRef\.current\?\.focus/);
  assert.match(source,/mixedSimulationEvidence\?\.masteryStatus === "mastered"\) && \([\s\S]*?<button ref=\{continueButtonRef\}[\s\S]*?Continue to the next survey site/);
  assert.match(css,/\.final-confidence-workspace \.ownership-confirmation input,[\s\S]*?width: 24px;[\s\S]*?height: 24px;/);
  assert.match(css,/\.final-confidence-entry-errors \{[\s\S]*?font-size: 8px;[\s\S]*?line-height: 10px;/);
  assert.match(css,/data-final-confidence-action="true"\][\s\S]*?height: 24px;/);
});
