import test from "node:test";
import assert from "node:assert/strict";
import primary from "../../curriculum/lessons/L-05-01/reference_primary_answers.json" with { type: "json" };
import transfer from "../../curriculum/lessons/L-05-01/reference_transfer_answers.json" with { type: "json" };
import { evaluatePortalExplanation, evaluatePortalScenario, getPortalExplanationFeedback, getPortalFeedback, portalDialogDescribedBy, portalDialogDescriptionIds, portalPrimary, portalTransfer, sanitizePortalEvidence, updatePortalEvidence } from "../src/portalOrientationExercise.js";

test("portal warning and checkpoint equivalent have ordered unique associations", () => { assert.equal(portalDialogDescribedBy, "portal-offline-warning portal-checkpoint-equivalent"); assert.equal(new Set(portalDialogDescriptionIds).size, 2); });
test("both portal rehearsals pass 16/16 across eight checkpoints", () => { for (const [form, scenarios, answers] of [["primary", portalPrimary, primary], ["transfer", portalTransfer, transfer]]) { assert.equal(scenarios.length, 8); for (const scenario of scenarios) assert.equal(evaluatePortalScenario(scenario.id, answers[scenario.id], form).score, 2); } });
test("deployment and owner-scoped cleanup near misses fail", () => { assert.equal(evaluatePortalScenario("P04", { decision: "catalog_entry_is_callable", reason: primary.P04.reason }, "primary").correctness.decision, false); assert.equal(evaluatePortalScenario("T08", { decision: transfer.T08.decision, reason: "cleanup_is_always_safe" }, "transfer").correctness.reason, false); });
test("closed note requires four safeguards", () => assert.equal(evaluatePortalExplanation({ scope: "verify tenant subscription role project and parent scope", deployment: "choose capability fit model named deployment and wait for ready", connection: "endpoint and deployment name are configuration credential is secret", cleanup: "wrong" }).score, 3));
test("neutral System scores remain separate from Teacher remediation", () => { const result = evaluatePortalScenario("T08", { decision: transfer.T08.decision, reason: "cleanup_is_always_safe" }, "transfer"); const feedback = getPortalFeedback(portalTransfer[7], result, 3); assert.equal(feedback.systemScore, "1/2 · CHOICE NOT YET COMPLETE."); assert.doesNotMatch(feedback.systemScore, /scope|cleanup|Teacher/i); assert.match(feedback.teacherRemediation, /owner-confirmed exact scope/i); const closed = getPortalExplanationFeedback(evaluatePortalExplanation({})); assert.equal(closed.systemScore, "0/4 · EXPLANATION NOT YET COMPLETE."); assert.match(closed.teacherRemediation, /scope.*cleanup/i); });
test("strict mastery stores no identifiers, credentials, prompts, responses, or free text", () => { let evidence = updatePortalEvidence(null, {}); for (const [form, scenarios, answers] of [["primary", portalPrimary, primary], ["transfer", portalTransfer, transfer]]) for (const scenario of scenarios) evidence = updatePortalEvidence(evidence, { form, scenarioId: scenario.id, correctness: evaluatePortalScenario(scenario.id, answers[scenario.id], form).correctness }); evidence = updatePortalEvidence(evidence, { form: "explanation", scenarioId: "explanation", correctness: { scope: true, deployment: true, connection: true, cleanup: true }, masteryStatus: "mastered" }); assert.equal(evidence.masteryStatus, "mastered"); const safe = sanitizePortalEvidence({ ...evidence, tenantId: "x", subscriptionId: "x", resourceGroup: "x", projectName: "x", endpoint: "x", deploymentName: "x", credential: "x", promptText: "x", modelResponse: "x", freeText: "x" }); for (const key of ["tenantId", "subscriptionId", "resourceGroup", "projectName", "endpoint", "deploymentName", "credential", "promptText", "modelResponse", "freeText"]) assert.equal(key in safe, false); });
