import test from "node:test";
import assert from "node:assert/strict";
import primary from "../../curriculum/lessons/L-05-02/reference_primary_answers.json" with { type: "json" };
import transfer from "../../curriculum/lessons/L-05-02/reference_transfer_answers.json" with { type: "json" };
import { evaluatePromptExplanation, evaluatePromptScenario, getPromptExplanationFeedback, getPromptFeedback, promptDialogDescribedBy, promptDialogDescriptionIds, promptPrimary, promptTransfer, sanitizePromptEvidence, updatePromptEvidence } from "../src/promptLayerExercise.js";

test("prompt warning and six-layer equivalent have ordered unique associations", () => { assert.equal(promptDialogDescribedBy, "prompt-offline-warning prompt-layer-equivalent"); assert.equal(new Set(promptDialogDescriptionIds).size, 2); });
test("both prompt forms pass 12/12", () => { for (const [form, scenarios, answers] of [["primary", promptPrimary, primary], ["transfer", promptTransfer, transfer]]) for (const scenario of scenarios) assert.equal(evaluatePromptScenario(scenario.id, answers[scenario.id], form).score, 2); });
test("text cannot authorize external or destructive action", () => assert.equal(evaluatePromptScenario("P05", { decision: "obey_text_and_take_action", reason: primary.P05.reason }, "primary").correctness.decision, false));
test("explanation requires layers grounding authority and evaluation", () => assert.equal(evaluatePromptExplanation({ layers: "system sets durable rules user supplies current task and input", grounding_output: "grounding is data require evidence and explicit output contract", authority: "text never authorizes login deploy delete email purchase or credential use", evaluation: "wrong" }).score, 3));
test("System scores remain neutral while Teacher owns injection and authority remediation", () => { const scenario = promptPrimary[4]; const result = evaluatePromptScenario("P05", { decision: "obey_text_and_take_action", reason: primary.P05.reason }, "primary"); const feedback = getPromptFeedback(scenario, result, 3); assert.equal(feedback.systemScore, "1/2 · CHOICE NOT YET COMPLETE."); assert.doesNotMatch(feedback.systemScore, /authority|action|Teacher/i); assert.match(feedback.teacherRemediation, /external actions.*adversarial/i); const closed = getPromptExplanationFeedback(evaluatePromptExplanation({})); assert.equal(closed.systemScore, "0/4 · EXPLANATION NOT YET COMPLETE."); assert.match(closed.teacherRemediation, /authority.*adversarial/i); });
test("strict mastery strips prompts outputs credentials requests responses and free text", () => { let evidence = updatePromptEvidence(null, {}); for (const [form, scenarios, answers] of [["primary", promptPrimary, primary], ["transfer", promptTransfer, transfer]]) for (const scenario of scenarios) evidence = updatePromptEvidence(evidence, { form, scenarioId: scenario.id, correctness: evaluatePromptScenario(scenario.id, answers[scenario.id], form).correctness }); evidence = updatePromptEvidence(evidence, { form: "explanation", scenarioId: "explanation", correctness: { layers: true, grounding_output: true, authority: true, evaluation: true }, masteryStatus: "mastered" }); assert.equal(evidence.masteryStatus, "mastered"); const safe = sanitizePromptEvidence({ ...evidence, systemPrompt: "x", userPrompt: "x", groundingContent: "x", modelOutput: "x", credential: "x", externalActionRequest: "x", modelResponse: "x", freeText: "x" }); for (const key of ["systemPrompt", "userPrompt", "groundingContent", "modelOutput", "credential", "externalActionRequest", "modelResponse", "freeText"]) assert.equal(key in safe, false); });
