import assert from "node:assert/strict";
import test from "node:test";
import { FIRST_RUN_RESPONSIVE_LAYOUTS,deriveInteractiveTarget,deriveResponsiveEvidence,getExpectedCanonicalWorldSize,parseObjectPosition,projectCoverGeometry,projectSourceRect } from "../src/responsiveImageProjection.js";
import { SEDIMENT_ABACUS_REGISTRY } from "../src/sedimentAbacus.js";
import { SEVERED_RELAY_SPINE_REGISTRY } from "../src/severedRelaySpine.js";

test("cover projection retains equal-aspect sources regardless of object position",()=>{for(const viewport of Object.values(FIRST_RUN_RESPONSIVE_LAYOUTS)){const world=getExpectedCanonicalWorldSize(viewport.width,viewport.height);for(const position of ["50% 50%","70% top","left bottom"]){const geometry=projectCoverGeometry({sourceWidth:3840,sourceHeight:2160,containerWidth:world.width,containerHeight:world.height,objectPosition:position});assert.deepEqual({...geometry.visibleSource},{x:0,y:0,width:3840,height:2160});assert.ok(Math.abs(geometry.renderedWidth-world.width)<1e-9);assert.ok(Math.abs(geometry.renderedHeight-world.height)<1e-9);}}});
test("cover projection derives real crop and object-position",()=>{const centered=projectCoverGeometry({sourceWidth:400,sourceHeight:400,containerWidth:1600,containerHeight:900,objectPosition:"50% 50%"});assert.deepEqual({...centered.visibleSource},{x:0,y:87.5,width:400,height:225});const top=projectCoverGeometry({sourceWidth:400,sourceHeight:400,containerWidth:1600,containerHeight:900,objectPosition:"center top"});assert.deepEqual({...top.visibleSource},{x:0,y:0,width:400,height:225});assert.deepEqual({...parseObjectPosition("70% top")},{x:.7,y:0});});
test("source projection clips and derives retained area",()=>{const geometry=projectCoverGeometry({sourceWidth:400,sourceHeight:400,containerWidth:1600,containerHeight:900});const result=projectSourceRect({x:0,y:0,width:400,height:200},geometry);assert.equal(result.visible.height,450);assert.equal(result.retainedArea,0.5625);});
test("interactive target expands symmetrically to 44 CSS px and clamps",()=>{const centered=deriveInteractiveTarget({x:5,y:5,width:10,height:10,centerX:10,centerY:10},320,180);assert.deepEqual({...centered},{x:0,y:0,width:44,height:44,contained:true});const large=deriveInteractiveTarget({x:50,y:40,width:100,height:80,centerX:100,centerY:80},320,180);assert.deepEqual({...large},{x:50,y:40,width:100,height:80,contained:true});});
test("malformed geometry fails closed",()=>{assert.equal(getExpectedCanonicalWorldSize(Number.NaN,100),null);assert.equal(projectCoverGeometry({sourceWidth:0,sourceHeight:1,containerWidth:1,containerHeight:1}),null);assert.equal(projectSourceRect({x:-1,y:0,width:1,height:1},projectCoverGeometry({sourceWidth:2,sourceHeight:2,containerWidth:2,containerHeight:2})),null);});
test("released Host 07 and 08 rectangles corroborate under derived projection",()=>{for(const registry of [SEDIMENT_ABACUS_REGISTRY,SEVERED_RELAY_SPINE_REGISTRY]){for(const viewport of Object.values(FIRST_RUN_RESPONSIVE_LAYOUTS)){const evidence=deriveResponsiveEvidence({viewport,relation:registry.relation,semanticTarget:registry.semanticTarget,essentialRects:[],protectedRects:[],objectFit:"cover",objectPosition:"50% 50%"});assert.ok(evidence);assert.equal(evidence.relation.retainedArea,1);assert.equal(evidence.semanticContainsPhysicalCenter,true);assert.equal(evidence.target.contained,true);assert.ok(evidence.target.width>=44);assert.ok(evidence.target.height>=44);}}});
