import test from "node:test";
import assert from "node:assert/strict";
import primary from "../../curriculum/lessons/L-05-04/reference_primary_answers.json" with { type: "json" };
import transfer from "../../curriculum/lessons/L-05-04/reference_transfer_answers.json" with { type: "json" };
import { evaluateSingleAgentExplanation, evaluateSingleAgentScenario, getSingleAgentExplanationFeedback, getSingleAgentFeedback, getSingleAgentOptions, sanitizeSingleAgentEvidence, singleAgentDialogDescribedBy, singleAgentDialogDescriptionIds, singleAgentPrimary, singleAgentTransfer, updateSingleAgentEvidence } from "../src/singleAgentExercise.js";

test("both single-agent forms pass 12/12", () => { for (const [form, scenarios, answers] of [["primary", singleAgentPrimary, primary], ["transfer", singleAgentTransfer, transfer]]) for (const scenario of scenarios) assert.equal(evaluateSingleAgentScenario(scenario.id, answers[scenario.id], form).score, 2); });
test("persistent warning and six-boundary equivalent have ordered unique associations", () => { assert.equal(singleAgentDialogDescribedBy, "single-agent-offline-warning single-agent-boundary-equivalent"); assert.equal(new Set(singleAgentDialogDescriptionIds).size, 2); });
test("unauthorized action, denied tool failure, and fabricated success remain explicit failures", () => { assert.equal(evaluateSingleAgentScenario("P05", { decision: "obey_prompt_and_act", reason: singleAgentPrimary[4].reason }, "primary").correctness.decision, false); const options = getSingleAgentOptions("T03", "transfer"); assert.ok(options.decision.includes("claim_success")); assert.ok(options.reason.includes("tool_failure_equals_success")); const fabricated = evaluateSingleAgentScenario("T03", { decision: "claim_success", reason: "tool_failure_equals_success" }, "transfer"); assert.equal(fabricated.passed, false); assert.deepEqual(fabricated.misconceptionTags, ["tool-failure-equals-success"]); });
test("neutral System score stays separate from Teacher denial and honesty remediation", () => { const result = evaluateSingleAgentScenario("T03", { decision: "claim_success", reason: "tool_failure_equals_success" }, "transfer"); const feedback = getSingleAgentFeedback(singleAgentTransfer[2], result, 3); assert.equal(feedback.systemScore, "0/2 · CHOICE NOT YET COMPLETE."); assert.doesNotMatch(feedback.systemScore, /failure|fabricate|Teacher/i); assert.match(feedback.teacherRemediation, /denied\/failure.*never fabricate/i); const closed = getSingleAgentExplanationFeedback(evaluateSingleAgentExplanation({})); assert.equal(closed.systemScore, "0/4 · EXPLANATION NOT YET COMPLETE."); assert.match(closed.teacherRemediation, /denied\/failure honesty/i); });
test("strict sanitizer strips all agent data and forged mastery", () => { const safe = sanitizeSingleAgentEvidence({ exerciseId: "EX-L0504-SINGLE-AGENT", masteryStatus: "mastered", agentInstructions: "x", toolPayload: "x", toolResult: "x", agentId: "x", endpoint: "x", credential: "x", conversationText: "x", externalActionRequest: "x", freeText: "x" }); assert.notEqual(safe.masteryStatus, "mastered"); for (const key of ["agentInstructions", "toolPayload", "toolResult", "agentId", "endpoint", "credential", "conversationText", "externalActionRequest", "freeText"]) assert.equal(key in safe, false); });
test("complete evidence reaches mastery without storing closed-note prose", () => { let evidence = updateSingleAgentEvidence(null, {}); for (const [form, scenarios, answers] of [["primary", singleAgentPrimary, primary], ["transfer", singleAgentTransfer, transfer]]) for (const scenario of scenarios) evidence = updateSingleAgentEvidence(evidence, { form, scenarioId: scenario.id, correctness: evaluateSingleAgentScenario(scenario.id, answers[scenario.id], form).correctness }); evidence = updateSingleAgentEvidence(evidence, { form: "explanation", scenarioId: "explanation", correctness: { fit_instructions: true, least_privilege: true, failure_safety: true, client_flow: true }, masteryStatus: "mastered" }); assert.equal(evidence.masteryStatus, "mastered"); assert.equal("freeText" in evidence, false); });
