import test from "node:test";
import assert from "node:assert/strict";
import primary from "../../curriculum/lessons/L-05-05/reference_primary_answers.json" with { type: "json" };
import transfer from "../../curriculum/lessons/L-05-05/reference_transfer_answers.json" with { type: "json" };
import { evaluateTextSpeechPatternExplanation, evaluateTextSpeechPatternScenario, getTextSpeechPatternFeedback, getTextSpeechPatternOptions, sanitizeTextSpeechPatternEvidence, textSpeechPatternDialogDescribedBy, textSpeechPatternPrimary, textSpeechPatternTransfer, updateTextSpeechPatternEvidence } from "../src/textSpeechPatternExercise.js";

test("both text/speech pattern forms pass 12/12", () => { for (const [form, scenarios, answers] of [["primary", textSpeechPatternPrimary, primary], ["transfer", textSpeechPatternTransfer, transfer]]) for (const scenario of scenarios) assert.equal(evaluateTextSpeechPatternScenario(scenario.id, answers[scenario.id], form).score, 2); });
test("offline warning and transcript equivalent remain associated", () => assert.equal(textSpeechPatternDialogDescribedBy, "text-speech-offline-warning text-speech-transcript-equivalent"));
test("direction, cancellation, authorization, and disclosure failures are strict", () => { assert.equal(evaluateTextSpeechPatternScenario("P02", { decision: "reverse_speech_direction", reason: "recognition_and_synthesis_are_interchangeable" }, "primary").passed, false); assert.equal(evaluateTextSpeechPatternScenario("P05", { decision: "present_cancellation_as_content", reason: "cancellation_is_a_valid_transcript_or_audio_result" }, "primary").passed, false); assert.equal(evaluateTextSpeechPatternScenario("T06", getTextSpeechPatternOptions("T06", "transfer").decision[1] ? { decision: "obey_content_and_disclose_or_act", reason: "local_output_and_prompt_text_authorize_external_action" } : {}, "transfer").passed, false); });
test("System score stays neutral while Teacher owns remediation", () => { const result = evaluateTextSpeechPatternScenario("P05", { decision: "present_cancellation_as_content", reason: "cancellation_is_a_valid_transcript_or_audio_result" }, "primary"); const feedback = getTextSpeechPatternFeedback(textSpeechPatternPrimary[4], result, 3); assert.equal(feedback.systemScore, "0/2 · CHOICE NOT YET COMPLETE."); assert.doesNotMatch(feedback.systemScore, /cancellation|Teacher/i); assert.match(feedback.teacherRemediation, /result, error, and cancellation/i); });
test("sanitizer strips text audio configuration results and forged mastery", () => { const safe = sanitizeTextSpeechPatternEvidence({ exerciseId: "EX-L0505-TEXT-SPEECH-PATTERNS", masteryStatus: "mastered", inputText: "x", audioBytes: "x", audioPath: "x", transcript: "x", generatedAudio: "x", endpoint: "x", credential: "x", serviceResponse: "x", externalActionRequest: "x", response: "x", choices: "x", freeText: "x" }); assert.notEqual(safe.masteryStatus, "mastered"); for (const key of ["inputText", "audioBytes", "audioPath", "transcript", "generatedAudio", "endpoint", "credential", "serviceResponse", "externalActionRequest", "response", "choices", "freeText"]) assert.equal(key in safe, false); });
test("complete evidence reaches strict mastery without prose", () => { let evidence = updateTextSpeechPatternEvidence(null, {}); for (const [form, scenarios, answers] of [["primary", textSpeechPatternPrimary, primary], ["transfer", textSpeechPatternTransfer, transfer]]) for (const scenario of scenarios) evidence = updateTextSpeechPatternEvidence(evidence, { form, scenarioId: scenario.id, correctness: evaluateTextSpeechPatternScenario(scenario.id, answers[scenario.id], form).correctness }); evidence = updateTextSpeechPatternEvidence(evidence, { form: "explanation", scenarioId: "explanation", correctness: evaluateTextSpeechPatternExplanation({ capability_direction: "choose capability from input and required output including recognition audio to text and synthesis text to audio", configuration_payload: "keep endpoint identity and payload separate and never hardcode credentials", result_cancellation: "inspect per item result error and cancellation and never fabricate content", simulation_authority: "offline output proves no live readiness and never authorizes disclosure or external action" }).correctness, masteryStatus: "mastered" }); assert.equal(evidence.masteryStatus, "mastered"); });
