import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { TIDAL_PATTERN_LOOM_COPY, TIDAL_PATTERN_LOOM_PATH, TIDAL_PATTERN_LOOM_REGISTRY, deriveTidalPatternLoomResponsiveEvidence, deriveTidalPatternLoomState, getTidalPatternLoomHotspot, isLegacyHost13LessonLauncherVisible, isTidalPatternLoomMeasurementPass, isTidalPatternLoomSourceIdentityPass } from "../src/tidalPatternLoom.js";

const source = { enabled: true, path: TIDAL_PATTERN_LOOM_PATH, sha256: "a".repeat(64), byteLength: 12000000, width: 3840, height: 2160, format: "png", color: "opaque-srgb-8", attemptId: "H13-1" };
const provenance = { sha256: source.sha256, byteLength: source.byteLength, promptId: "HOST13-GEN-PROMPT-H13-1", promptBytes: 1610, promptSha256: "7749b50cc8d9870d2531250c9149165a438dfd6a3bdfb0e40005c27f47f44296", cliSha256: "c2cdb05244ad9a3dcb8731988790ea6a06a59ab3c062c0f872b35f4ad7d20b05" };
function registry() {
  const spans = [{ x: 1280, y: 600, width: 1150, height: 120, angleDegrees: -18, depthPlane: 1 }, { x: 1450, y: 900, width: 1100, height: 120, angleDegrees: 8, depthPlane: 2 }, { x: 1200, y: 1160, width: 1300, height: 120, angleDegrees: 24, depthPlane: 3 }];
  const collarPairs = [{ start: { x: 1200, y: 540, width: 120, height: 220 }, end: { x: 2300, y: 540, width: 120, height: 220 } }, { start: { x: 1400, y: 840, width: 120, height: 220 }, end: { x: 2450, y: 840, width: 120, height: 220 } }, { start: { x: 1120, y: 1100, width: 120, height: 220 }, end: { x: 2420, y: 1100, width: 120, height: 220 } }];
  return { source, relation: { x: 1075, y: 346, width: 1690, height: 1468, centerX: 1920, centerY: 1080 }, dryApproach: { x: 1100, y: 1200, width: 600, height: 620 }, spans, collarPairs, loadContacts: [{ x: 1250, y: 500, width: 220, height: 300 }, { x: 1780, y: 780, width: 220, height: 300 }, { x: 2280, y: 1000, width: 220, height: 300 }], residue: { x: 1300, y: 480, width: 1200, height: 900 }, waterline: { x: 1080, y: 1300, width: 1680, height: 400 }, semanticTarget: { x: 980, y: 260, width: 1880, height: 1640 }, labelAnchor: { x: 1010, y: 290, width: 1820, height: 1580, insetOuterCss: 3, insetTextCss: 5 }, protected: { host12: null, returnRoute: null, host14: null, witness: null } };
}

test("Host 13 starts inert and null-first", () => { assert.equal(TIDAL_PATTERN_LOOM_REGISTRY.source.enabled, false); assert.equal(isTidalPatternLoomSourceIdentityPass(), false); assert.equal(isTidalPatternLoomMeasurementPass(), false); assert.equal(getTidalPatternLoomHotspot(), null); for (const [key, value] of Object.entries(TIDAL_PATTERN_LOOM_COPY)) if (key !== "name") assert.equal(value, null); });
test("Host 13 accepts only the frozen attempt domain and cap", () => { assert.equal(isTidalPatternLoomSourceIdentityPass(source, provenance), true); assert.equal(isTidalPatternLoomSourceIdentityPass({ ...source, attemptId: "H13-9" }, provenance), false); assert.equal(isTidalPatternLoomSourceIdentityPass({ ...source, byteLength: 30000001 }, provenance), false); });
test("Host 13 requires the complete physical sentence and six derived layouts", () => { const selected = registry(); assert.equal(isTidalPatternLoomMeasurementPass(selected), true); assert.equal(Object.keys(deriveTidalPatternLoomResponsiveEvidence(selected)).length, 6); assert.ok(getTidalPatternLoomHotspot(selected)); assert.equal(isTidalPatternLoomMeasurementPass({ ...selected, loadContacts: selected.loadContacts.slice(0, 2) }), false); assert.equal(isTidalPatternLoomMeasurementPass({ ...selected, spans: selected.spans.map((span) => ({ ...span, angleDegrees: 0 })) }), false); });
test("Host 13 state fails closed and source enablement retires its launchers", () => { assert.equal(isLegacyHost13LessonLauncherVisible(), true); assert.equal(isLegacyHost13LessonLauncherVisible(source), false); assert.equal(deriveTidalPatternLoomState({ predecessorComplete: true, registry: registry(), provenance, decodedImage: { complete: true, naturalWidth: 3840, naturalHeight: 2160 } }), "available"); assert.equal(deriveTidalPatternLoomState({ predecessorComplete: false, registry: registry(), provenance, decodedImage: { complete: true, naturalWidth: 3840, naturalHeight: 2160 } }), "hidden"); });
test("App guards only Text and Speech and Visual Pattern generic launchers", async () => { const app = await readFile(new URL("../src/App.jsx", import.meta.url), "utf8"); assert.match(app, /isLegacyHost13LessonLauncherVisible/); assert.equal((app.match(/legacyHost13LessonLauncherVisible&&pendingAdvance/g) ?? []).length, 2); assert.match(app, /pendingAdvance&&scene\.id==="ruins"&&visualPatternEvidence\?\.masteryStatus==="mastered"&&objectiveLedgerEvidence/); });
