import test from "node:test";
import assert from "node:assert/strict";
import primary from "../../curriculum/lessons/L-04-03/reference_primary_answers.json" with { type: "json" };
import transfer from "../../curriculum/lessons/L-04-03/reference_transfer_answers.json" with { type: "json" };
import { evaluateVisualExplanation, evaluateVisualScenario, getVisualExplanationFeedback, getVisualFeedback, sanitizeVisualEvidence, updateVisualEvidence, visualDialogDescribedBy, visualDialogDescriptionIds, visualPrimaryScenarios, visualTransferScenarios } from "../src/visualWorkloadExercise.js";

test("visual dialog descriptions include offline, text-equivalent, and deprecation warnings", () => { assert.equal(visualDialogDescribedBy, "visual-offline-warning visual-text-equivalent visual-deprecation-warning"); assert.equal(new Set(visualDialogDescriptionIds).size, 3); });
test("both visual forms pass 12/12 and cover four workloads plus two client-flow items", () => { for (const [form, scenarios, answers] of [["primary", visualPrimaryScenarios, primary], ["transfer", visualTransferScenarios, transfer]]) { assert.equal(scenarios.length, 6); assert.equal(scenarios.filter((scenario) => scenario.topic === "client_flow").length, 2); for (const scenario of scenarios) assert.equal(evaluateVisualScenario(scenario.id, answers[scenario.id], form).score, 2); } });
test("wrong selection produces strict Teacher remediation separate from System score", () => { const scenario = visualPrimaryScenarios[5]; const result = evaluateVisualScenario("P06", { decision: primary.P06.decision, reason: "generated_media_and_analysis_records_are_interchangeable" }, "primary"); const feedback = getVisualFeedback(scenario, result, 3); assert.equal(feedback.systemScore, "1/2 · CHOICE NOT YET COMPLETE."); assert.match(feedback.teacherRemediation, /path.*JSON.*generated-media/i); });
test("closed-note explanation requires all four dimensions", () => { const result = evaluateVisualExplanation({}); const feedback = getVisualExplanationFeedback(result); assert.equal(feedback.systemScore, "0/4 · EXPLANATION NOT YET COMPLETE."); assert.match(feedback.teacherRemediation, /existing.*JSON-versus-media/i); });
test("strict sanitizer rejects forged mastery and strips media, paths, prompts, outputs, and free text", () => { const forged = sanitizeVisualEvidence({ exerciseId: "EX-L0403-VISUAL-WORKLOADS", masteryStatus: "mastered", mediaBytes: "private", mediaPath: "private", generationPrompt: "private", analysisResultBody: "private", runtimeOutput: "private", freeText: "private" }); assert.notEqual(forged.masteryStatus, "mastered"); for (const key of ["mediaBytes", "mediaPath", "generationPrompt", "analysisResultBody", "runtimeOutput", "freeText"]) assert.equal(key in forged, false); });
test("complete sanitized evidence can reach strict mastery", () => { let evidence = updateVisualEvidence(null, {}); for (const [form, scenarios, answers] of [["primary", visualPrimaryScenarios, primary], ["transfer", visualTransferScenarios, transfer]]) for (const scenario of scenarios) evidence = updateVisualEvidence(evidence, { form, scenarioId: scenario.id, correctness: evaluateVisualScenario(scenario.id, answers[scenario.id], form).correctness }); evidence = updateVisualEvidence(evidence, { form: "explanation", scenarioId: "explanation", correctness: { existing_or_new: true, input_modalities: true, required_output: true, media_handling: true }, masteryStatus: "mastered" }); assert.equal(evidence.masteryStatus, "mastered"); });
