import exerciseAsset from "../../curriculum/lessons/L-04-04/exercise.json" with { type: "json" };
import scenarioBank from "../../curriculum/lessons/L-04-04/scenario_bank.json" with { type: "json" };
import answerKey from "../../curriculum/lessons/L-04-04/answer_key.json" with { type: "json" };
export const extractionWorkloadExercise = exerciseAsset; export const extractionPrimaryScenarios = scenarioBank.forms.primary; export const extractionTransferScenarios = scenarioBank.forms.transfer; export const extractionDimensions = exerciseAsset.dimensions; export const extractionExplanationDimensions = ["modality", "schema", "missing_value", "evidence_review"];
export const extractionDialogDescriptionIds = ["extraction-offline-warning", "extraction-text-equivalent"];
export const extractionDialogDescribedBy = extractionDialogDescriptionIds.join(" ");
const wrongByTopic = { document_or_form_extraction: { decision: "summarization", reason: "a_summary_is_the_same_as_named_fields" }, image_extraction: { decision: "image_analysis", reason: "a_general_description_is_a_field_schema" }, audio_extraction: { decision: "transcription_only", reason: "a_transcript_is_the_final_structured_record" }, video_extraction: { decision: "captioning_only", reason: "captions_alone_are_the_requested_schema" }, integrity: { decision: "guess_value", reason: "every_schema_field_must_be_filled_even_without_evidence" } };
const tags = { document_or_form_extraction: "summary-is-field-schema", image_extraction: "vision-description-is-extraction", audio_extraction: "audio-extraction-is-only-transcription", video_extraction: "video-extraction-is-only-captioning", integrity: "invented-missing-value" }; const validTags = new Set(exerciseAsset.misconception_tags); const all = [...extractionPrimaryScenarios, ...extractionTransferScenarios];
export function getExtractionOptions(id, form = id?.startsWith("T") ? "transfer" : "primary") { const s = scenarioBank.forms[form].find((x) => x.id === id); const e = answerKey.forms[form][id]; const w = wrongByTopic[s.topic]; return { decision: [e.decision, w.decision], reason: [e.reason, w.reason] }; }
export function evaluateExtractionScenario(id, response, form = id?.startsWith("T") ? "transfer" : "primary") { const e = answerKey.forms[form]?.[id]; const s = scenarioBank.forms[form].find((x) => x.id === id); if (!e || !s) return null; const correctness = Object.fromEntries(extractionDimensions.map((k) => [k, response[k] === e[k]])); const passed = Object.values(correctness).every(Boolean); return { correctness, score: Object.values(correctness).filter(Boolean).length, passed, misconceptionTags: passed ? [] : [tags[s.topic]] }; }
function norm(v) { return String(v ?? "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""); }
export function evaluateExtractionExplanation(response) { const e = { modality: "choose_document_image_audio_or_video_source", schema: "define_field_names_types_and_descriptions_before_analysis", missing_value: "preserve_null_or_missing_never_invent_value", evidence_review: "retain_provenance_and_confidence_for_human_review" }; const correctness = Object.fromEntries(extractionExplanationDimensions.map((k) => [k, norm(response[k]) === e[k]])); return { correctness, score: Object.values(correctness).filter(Boolean).length, passed: Object.values(correctness).every(Boolean) }; }
export function extractionRemediation(s, r, l) { const missed = extractionDimensions.filter((k) => !r.correctness[k]); if (l <= 1) return `Review ${missed.join(" and ")}: name the input modality and required fields.`; if (l === 2) return `Contrast a general description/transcript with schema extraction for this ${s.topic.replaceAll("_", " ")} item.`; return "Inspect the field schema; preserve missing/null and retain evidence for review instead of inventing a value."; }
export function getExtractionFeedback(s, r, l) { if (!r) return { systemScore: "Awaiting both extraction dimensions.", teacherRemediation: null }; return { systemScore: `${r.score}/2 · ${r.passed ? "CHOICE PASS · both dimensions confirmed." : "CHOICE NOT YET COMPLETE."}`, teacherRemediation: r.passed ? null : extractionRemediation(s, r, l) }; }
export function getExtractionExplanationFeedback(r) { if (!r) return { systemScore: "Awaiting the learner's four-part extraction flow.", teacherRemediation: null }; return { systemScore: `${r.score}/4 · ${r.passed ? "EXPLANATION PASS · all four dimensions confirmed." : "EXPLANATION NOT YET COMPLETE."}`, teacherRemediation: r.passed ? null : "Trace modality, declared schema, null/missing policy, and evidence review without inventing a value." }; }
function complete(c, scenarios) { return scenarios.every((s) => extractionDimensions.every((k) => c[s.id]?.[k] === true)); }
export function sanitizeExtractionEvidence(v) { if (!v || typeof v !== "object" || v.exerciseId !== exerciseAsset.exercise_id) return null; const dimensionCorrectness = {}; for (const s of [...all, { id: "explanation", dimensions: extractionExplanationDimensions }]) { const keys = s.dimensions || extractionDimensions; if (v.dimensionCorrectness?.[s.id]) dimensionCorrectness[s.id] = Object.fromEntries(keys.filter((k) => typeof v.dimensionCorrectness[s.id][k] === "boolean").map((k) => [k, v.dimensionCorrectness[s.id][k]])); } const strict = complete(dimensionCorrectness, extractionPrimaryScenarios) && complete(dimensionCorrectness, extractionTransferScenarios) && extractionExplanationDimensions.every((k) => dimensionCorrectness.explanation?.[k] === true); let masteryStatus = ["in_progress", "remediation_required", "primary_complete", "transfer_complete", "mastered"].includes(v.masteryStatus) ? v.masteryStatus : "in_progress"; if (masteryStatus === "mastered" && !strict) masteryStatus = complete(dimensionCorrectness, extractionTransferScenarios) ? "transfer_complete" : complete(dimensionCorrectness, extractionPrimaryScenarios) ? "primary_complete" : "in_progress"; return { exerciseId: exerciseAsset.exercise_id, lessonId: exerciseAsset.lesson_id, activityId: exerciseAsset.activity_id, assessmentId: exerciseAsset.assessment_id, objectiveIds: [...exerciseAsset.objective_ids], skillIds: [...exerciseAsset.skill_ids], form: ["primary", "transfer", "explanation"].includes(v.form) ? v.form : "primary", dimensionCorrectness, attemptCount: Math.min(99, Math.max(0, Number.isInteger(v.attemptCount) ? v.attemptCount : 0)), hintLevel: Math.min(3, Math.max(0, Number.isInteger(v.hintLevel) ? v.hintLevel : 0)), confidence: ["low", "medium", "high"].includes(v.confidence) ? v.confidence : null, misconceptionTags: Array.isArray(v.misconceptionTags) ? [...new Set(v.misconceptionTags.filter((t) => validTags.has(t)))] : [], masteryStatus }; }
export function updateExtractionEvidence(previous, changes = {}) { const safe = sanitizeExtractionEvidence(previous) || sanitizeExtractionEvidence({ exerciseId: exerciseAsset.exercise_id }); const dimensionCorrectness = { ...safe.dimensionCorrectness }; if (changes.scenarioId && changes.correctness) dimensionCorrectness[changes.scenarioId] = changes.correctness; return sanitizeExtractionEvidence({ ...safe, form: changes.form || safe.form, dimensionCorrectness, attemptCount: safe.attemptCount + (changes.incrementAttempt ? 1 : 0), hintLevel: Math.max(safe.hintLevel, changes.hintLevel || 0), confidence: changes.confidence || safe.confidence, misconceptionTags: changes.clearMisconceptionTags ? [] : [...safe.misconceptionTags, ...(changes.misconceptionTags || [])], masteryStatus: changes.masteryStatus || safe.masteryStatus }); }
