import { FIRST_RUN_RESPONSIVE_LAYOUTS } from "./responsiveImageProjection.js";
export const QUIET_OUTER_MARGIN_COPY = Object.freeze({ alt: "Pressure-bent membranes, porous mineral foam, residue seams, and dense anchors continue beneath an unchanged quiet horizon at the outer margin." });
export const EQUAL_DIGNITY_HORIZON_COPY = Object.freeze({ alt: "A stable ceramic outer margin faces a neutral horizon while membranes, condensation, residue, and distant heat continue without acknowledgement or change." });
const source = Object.freeze({ enabled: true, path: "Visual Direction/Production Masters/2026-08-14-first-run-host39/host39-environment-master-v1.png", sourceId: "HA-IMG-H39-v1", bytes: 2968446, sha256: "217e6c0fd4e570d6942d10f1963aab00de47fb359cd6ba4c846f087edb7316ae", width: 1920, height: 1080, format: "png", color: "opaque-srgb-8" });
const provenance = Object.freeze({ schema: "horizon.image-toolkit.production-master.v1", path: source.path, sourceId: source.sourceId, bytes: source.bytes, sha256: source.sha256 });
export const QUIET_OUTER_MARGIN_REGISTRY = Object.freeze({ schema: "horizon.quiet-outer-margin.v1", source, provenance, layouts: Object.freeze(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: QUIET_OUTER_MARGIN_COPY });
const source40 = Object.freeze({ enabled: true, path: "Visual Direction/Production Masters/2026-08-14-first-run-host40/host40-environment-master-v1.png", sourceId: "HA-IMG-H40-v1", bytes: 2988801, sha256: "6eea0cd4deadef26b3b334a28a75470670040d7b1927fd1affcd49b38bbed54b", width: 1920, height: 1080, format: "png", color: "opaque-srgb-8" });
const provenance40 = Object.freeze({ schema: "horizon.image-toolkit.production-master.v1", path: source40.path, sourceId: source40.sourceId, bytes: source40.bytes, sha256: source40.sha256 });
export const EQUAL_DIGNITY_HORIZON_REGISTRY = Object.freeze({ schema: "horizon.equal-dignity-horizon.v1", source: source40, provenance: provenance40, layouts: Object.freeze(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: EQUAL_DIGNITY_HORIZON_COPY });
export function auditQuietOuterMargin(registry = QUIET_OUTER_MARGIN_REGISTRY) { const candidate = registry?.source; return Object.freeze({ source: candidate?.enabled === true && Object.keys(source).every((key) => candidate[key] === source[key]), provenance: provenance.schema === registry?.provenance?.schema && ["path", "sourceId", "bytes", "sha256"].every((key) => registry.provenance[key] === candidate?.[key]), layouts: JSON.stringify(registry?.layouts) === JSON.stringify(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: registry?.copy === QUIET_OUTER_MARGIN_COPY }); }
export function deriveQuietOuterMarginState({ registry = QUIET_OUTER_MARGIN_REGISTRY, decodedImage } = {}) { return Object.values(auditQuietOuterMargin(registry)).every(Boolean) && decodedImage?.complete === true && decodedImage.naturalWidth === 1920 && decodedImage.naturalHeight === 1080 ? "available" : "hidden"; }
export function auditEqualDignityHorizon(registry = EQUAL_DIGNITY_HORIZON_REGISTRY) { const candidate = registry?.source; return Object.freeze({ source: candidate?.enabled === true && Object.keys(source40).every((key) => candidate[key] === source40[key]), provenance: provenance40.schema === registry?.provenance?.schema && ["path", "sourceId", "bytes", "sha256"].every((key) => registry.provenance[key] === candidate?.[key]), layouts: JSON.stringify(registry?.layouts) === JSON.stringify(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: registry?.copy === EQUAL_DIGNITY_HORIZON_COPY }); }
export function deriveEqualDignityHorizonState({ registry = EQUAL_DIGNITY_HORIZON_REGISTRY, decodedImage } = {}) { return Object.values(auditEqualDignityHorizon(registry)).every(Boolean) && decodedImage?.complete === true && decodedImage.naturalWidth === 1920 && decodedImage.naturalHeight === 1080 ? "available" : "hidden"; }
