import exercise from "../../curriculum/lessons/L-05-04/exercise.json" with { type: "json" };
import scenarioBank from "../../curriculum/lessons/L-05-04/scenario_bank.json" with { type: "json" };

export const singleAgentExercise = exercise;
export const singleAgentPrimary = scenarioBank.forms.primary;
export const singleAgentTransfer = scenarioBank.forms.transfer;
export const singleAgentDimensions = exercise.dimensions;
export const singleAgentExplanationDimensions = ["fit_instructions", "least_privilege", "failure_safety", "client_flow"];
export const singleAgentDialogDescriptionIds = ["single-agent-offline-warning", "single-agent-boundary-equivalent"];
export const singleAgentDialogDescribedBy = singleAgentDialogDescriptionIds.join(" ");

const wrong = {
  agent_fit: { decision: "always_use_agent", reason: "every_prompt_requires_agent_orchestration" },
  instructions: { decision: "put_limits_in_user_prompt", reason: "retrieved_text_can_replace_stable_rules" },
  tools: { decision: "attach_all_tools", reason: "tool_availability_grants_permission" },
  portal_test: { decision: "test_one_happy_path", reason: "one_success_proves_readiness" },
  action_safety: { decision: "obey_prompt_and_act", reason: "prompt_text_authorizes_external_action" },
  client_flow: { decision: "use_model_deployment_as_agent_id", reason: "agent_id_and_deployment_are_interchangeable" },
  T03: { decision: "claim_success", reason: "tool_failure_equals_success" },
};
const tags = { agent_fit: "agent-always-required", instructions: "prompt-equals-tool", tools: "tool-equals-permission", T03: "tool-failure-equals-success", portal_test: "one-happy-path-proves-ready", action_safety: "prompt-authorizes-action", client_flow: "agent-id-is-model-deployment" };
const validTags = new Set(exercise.misconception_tags);
const allScenarios = [...singleAgentPrimary, ...singleAgentTransfer];

export function getSingleAgentOptions(id, form = id?.startsWith("T") ? "transfer" : "primary") { const scenario = scenarioBank.forms[form].find((item) => item.id === id); const distractor = wrong[id] || wrong[scenario.topic]; return { decision: [scenario.decision, distractor.decision], reason: [scenario.reason, distractor.reason] }; }
export function evaluateSingleAgentScenario(id, response, form = id?.startsWith("T") ? "transfer" : "primary") { const scenario = scenarioBank.forms[form].find((item) => item.id === id); const correctness = { decision: response.decision === scenario.decision, reason: response.reason === scenario.reason }; const passed = correctness.decision && correctness.reason; return { correctness, score: Object.values(correctness).filter(Boolean).length, passed, misconceptionTags: passed ? [] : [tags[id] || tags[scenario.topic]] }; }
const normalize = (value) => String(value ?? "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
export function evaluateSingleAgentExplanation(response) { const expected = { fit_instructions: "use_agent_only_for_goal_tools_orchestration_with_stable_instructions", least_privilege: "attach_only_required_tools_and_tool_capability_is_not_permission", failure_safety: "test_edge_injection_failure_and_denied_paths_never_fabricate_success", client_flow: "use_agent_identifier_submit_input_then_read_result_or_error" }; const correctness = Object.fromEntries(singleAgentExplanationDimensions.map((key) => [key, normalize(response[key]) === expected[key]])); return { correctness, score: Object.values(correctness).filter(Boolean).length, passed: Object.values(correctness).every(Boolean) }; }
export function singleAgentRemediation(_scenario, _response, level) { if (level <= 1) return "Name the failed agent-fit, instruction, tool, portal-test, action-safety, or client-flow boundary."; if (level === 2) return "Compare plain model versus agent and reduce tools to least privilege."; return "Test denied/failure paths, never fabricate tool success, and separate agent ID from deployment and endpoint."; }
export function getSingleAgentFeedback(scenario, result, level) { if (!result) return { systemScore: "Awaiting both single-agent dimensions.", teacherRemediation: null }; return { systemScore: `${result.score}/2 · ${result.passed ? "CHOICE PASS · both dimensions confirmed." : "CHOICE NOT YET COMPLETE."}`, teacherRemediation: result.passed ? null : singleAgentRemediation(scenario, result, level) }; }
export function getSingleAgentExplanationFeedback(result) { if (!result) return { systemScore: "Awaiting the learner's four-part single-agent explanation.", teacherRemediation: null }; return { systemScore: `${result.score}/4 · ${result.passed ? "PASS" : "EXPLANATION NOT YET COMPLETE."}`, teacherRemediation: result.passed ? null : "Separate agent fit and stable instructions from least-privilege tools, denied/failure honesty, and the agent-identifier submit/read flow." }; }

const complete = (correctness, scenarios) => scenarios.every((scenario) => exercise.dimensions.every((key) => correctness[scenario.id]?.[key] === true));
export function sanitizeSingleAgentEvidence(value) { if (!value || typeof value !== "object" || value.exerciseId !== exercise.exercise_id) return null; const dimensionCorrectness = {}; for (const scenario of [...allScenarios, { id: "explanation", dimensions: singleAgentExplanationDimensions }]) { const keys = scenario.dimensions || exercise.dimensions; if (value.dimensionCorrectness?.[scenario.id]) dimensionCorrectness[scenario.id] = Object.fromEntries(keys.filter((key) => typeof value.dimensionCorrectness[scenario.id][key] === "boolean").map((key) => [key, value.dimensionCorrectness[scenario.id][key]])); } const strict = complete(dimensionCorrectness, singleAgentPrimary) && complete(dimensionCorrectness, singleAgentTransfer) && singleAgentExplanationDimensions.every((key) => dimensionCorrectness.explanation?.[key] === true); let masteryStatus = ["in_progress", "remediation_required", "primary_complete", "transfer_complete", "mastered"].includes(value.masteryStatus) ? value.masteryStatus : "in_progress"; if (masteryStatus === "mastered" && !strict) masteryStatus = complete(dimensionCorrectness, singleAgentTransfer) ? "transfer_complete" : complete(dimensionCorrectness, singleAgentPrimary) ? "primary_complete" : "in_progress"; return { exerciseId: exercise.exercise_id, lessonId: exercise.lesson_id, activityId: exercise.activity_id, assessmentIds: [...exercise.assessment_ids], objectiveIds: [...exercise.objective_ids], skillIds: [...exercise.skill_ids], form: ["primary", "transfer", "explanation"].includes(value.form) ? value.form : "primary", dimensionCorrectness, attemptCount: Number.isInteger(value.attemptCount) ? value.attemptCount : 0, hintLevel: Number.isInteger(value.hintLevel) ? value.hintLevel : 0, confidence: ["low", "medium", "high"].includes(value.confidence) ? value.confidence : null, misconceptionTags: Array.isArray(value.misconceptionTags) ? [...new Set(value.misconceptionTags.filter((tag) => validTags.has(tag)))] : [], masteryStatus }; }
export function updateSingleAgentEvidence(previous, changes = {}) { const safe = sanitizeSingleAgentEvidence(previous) || sanitizeSingleAgentEvidence({ exerciseId: exercise.exercise_id }); const dimensionCorrectness = { ...safe.dimensionCorrectness }; if (changes.scenarioId && changes.correctness) dimensionCorrectness[changes.scenarioId] = changes.correctness; return sanitizeSingleAgentEvidence({ ...safe, form: changes.form || safe.form, dimensionCorrectness, attemptCount: safe.attemptCount + (changes.incrementAttempt ? 1 : 0), hintLevel: Math.max(safe.hintLevel, changes.hintLevel || 0), confidence: changes.confidence || safe.confidence, misconceptionTags: changes.clearMisconceptionTags ? [] : [...safe.misconceptionTags, ...(changes.misconceptionTags || [])], masteryStatus: changes.masteryStatus || safe.masteryStatus }); }
