import exerciseAsset from "../../curriculum/lessons/L-04-02/exercise.json" with { type: "json" };
import scenarioBank from "../../curriculum/lessons/L-04-02/scenario_bank.json" with { type: "json" };
import answerKey from "../../curriculum/lessons/L-04-02/answer_key.json" with { type: "json" };
export const speechWorkloadExercise = exerciseAsset; export const speechPrimaryScenarios = scenarioBank.forms.primary; export const speechTransferScenarios = scenarioBank.forms.transfer; export const speechDimensions = exerciseAsset.dimensions; export const speechExplanationDimensions = ["direction", "workload", "file_binding", "result_branch"];
const distractors = { speech_recognition: { decision: "speech_synthesis", reason: "spoken_audio_is_generated_from_text" }, speech_synthesis: { decision: "speech_recognition", reason: "written_text_is_a_recognition_input" }, multimodal_spoken_prompt: { decision: "speech_recognition", reason: "every_spoken_question_only_needs_a_transcript" }, P04: { decision: "configure_audio_file_as_output", reason: "recognition_writes_transcript_into_the_audio_input" }, P05: { decision: "configure_audio_file_as_input", reason: "synthesis_reads_generated_audio_from_the_text_input" }, P06: { decision: "assume_successful_content", reason: "cancellation_is_valid_content" }, T04: { decision: "bind_recognizer_to_output_file", reason: "recognition_output_file_is_the_audio_source" }, T05: { decision: "bind_synthesizer_to_input_file", reason: "synthesis_input_audio_contains_the_written_text" }, T06: { decision: "treat_result_as_content", reason: "non_success_reasons_can_be_ignored" } };
const tags = { speech_recognition: "recognition-is-synthesis", speech_synthesis: "synthesis-is-recognition", multimodal_spoken_prompt: "speech-service-is-any-multimodal-model", P04: "output-file-is-input-file", T04: "output-file-is-input-file", P05: "output-file-is-input-file", T05: "output-file-is-input-file", P06: "ignores-cancellation", T06: "ignores-cancellation" }; const validTags = new Set(exerciseAsset.misconception_tags); const all = [...speechPrimaryScenarios, ...speechTransferScenarios];
export function getSpeechOptions(id, form = id?.startsWith("T") ? "transfer" : "primary") { const s = scenarioBank.forms[form].find((x) => x.id === id); const e = answerKey.forms[form][id]; const w = distractors[id] || distractors[s.topic]; return { decision: [e.decision, w.decision], reason: [e.reason, w.reason] }; }
export function evaluateSpeechScenario(id, response, form = id?.startsWith("T") ? "transfer" : "primary") { const e = answerKey.forms[form]?.[id]; if (!e) return null; const correctness = Object.fromEntries(speechDimensions.map((k) => [k, response[k] === e[k]])); const passed = Object.values(correctness).every(Boolean); const s = scenarioBank.forms[form].find((x) => x.id === id); return { correctness, score: Object.values(correctness).filter(Boolean).length, passed, misconceptionTags: passed ? [] : [tags[id] || tags[s.topic]] }; }
function norm(v) { return String(v ?? "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""); }
export function evaluateSpeechExplanation(response) { const e = { direction: "spoken_audio_to_text_is_recognition_text_to_audio_is_synthesis", workload: "spoken_general_model_question_is_multimodal_prompt_flow", file_binding: "recognition_reads_input_file_synthesis_writes_output_file", result_branch: "inspect_result_reason_handle_success_or_cancellation" }; const correctness = Object.fromEntries(speechExplanationDimensions.map((k) => [k, norm(response[k]) === e[k]])); return { correctness, score: Object.values(correctness).filter(Boolean).length, passed: Object.values(correctness).every(Boolean) }; }
export function speechRemediation(s, r, l) { const missed = speechDimensions.filter((k) => !r.correctness[k]); if (l <= 1) return `Review ${missed.join(" and ")}: name input modality and required output.`; if (l === 2) return `Contrast Speech direction with deployed multimodal interaction for this ${s.topic.replaceAll("_", " ")} card.`; return "Trace input-file versus output-file direction, then branch on success or cancellation."; }
function complete(c, scenarios) { return scenarios.every((s) => speechDimensions.every((k) => c[s.id]?.[k] === true)); }
export function sanitizeSpeechEvidence(v) { if (!v || typeof v !== "object" || v.exerciseId !== exerciseAsset.exercise_id) return null; const dimensionCorrectness = {}; for (const s of [...all, { id: "explanation", dimensions: speechExplanationDimensions }]) { const keys = s.dimensions || speechDimensions; if (v.dimensionCorrectness?.[s.id]) dimensionCorrectness[s.id] = Object.fromEntries(keys.filter((k) => typeof v.dimensionCorrectness[s.id][k] === "boolean").map((k) => [k, v.dimensionCorrectness[s.id][k]])); } const strict = complete(dimensionCorrectness, speechPrimaryScenarios) && complete(dimensionCorrectness, speechTransferScenarios) && speechExplanationDimensions.every((k) => dimensionCorrectness.explanation?.[k] === true); let masteryStatus = ["in_progress", "remediation_required", "primary_complete", "transfer_complete", "mastered"].includes(v.masteryStatus) ? v.masteryStatus : "in_progress"; if (masteryStatus === "mastered" && !strict) masteryStatus = complete(dimensionCorrectness, speechTransferScenarios) ? "transfer_complete" : complete(dimensionCorrectness, speechPrimaryScenarios) ? "primary_complete" : "in_progress"; return { exerciseId: exerciseAsset.exercise_id, lessonId: exerciseAsset.lesson_id, activityId: exerciseAsset.activity_id, assessmentIds: [...exerciseAsset.assessment_ids], objectiveIds: [...exerciseAsset.objective_ids], skillIds: [...exerciseAsset.skill_ids], form: ["primary", "transfer", "explanation"].includes(v.form) ? v.form : "primary", dimensionCorrectness, attemptCount: Math.min(99, Math.max(0, Number.isInteger(v.attemptCount) ? v.attemptCount : 0)), hintLevel: Math.min(3, Math.max(0, Number.isInteger(v.hintLevel) ? v.hintLevel : 0)), confidence: ["low", "medium", "high"].includes(v.confidence) ? v.confidence : null, misconceptionTags: Array.isArray(v.misconceptionTags) ? [...new Set(v.misconceptionTags.filter((t) => validTags.has(t)))] : [], masteryStatus }; }
export function updateSpeechEvidence(previous, changes = {}) { const safe = sanitizeSpeechEvidence(previous) || sanitizeSpeechEvidence({ exerciseId: exerciseAsset.exercise_id }); const dimensionCorrectness = { ...safe.dimensionCorrectness }; if (changes.scenarioId && changes.correctness) dimensionCorrectness[changes.scenarioId] = changes.correctness; return sanitizeSpeechEvidence({ ...safe, form: changes.form || safe.form, dimensionCorrectness, attemptCount: safe.attemptCount + (changes.incrementAttempt ? 1 : 0), hintLevel: Math.max(safe.hintLevel, changes.hintLevel || 0), confidence: changes.confidence || safe.confidence, misconceptionTags: changes.clearMisconceptionTags ? [] : [...safe.misconceptionTags, ...(changes.misconceptionTags || [])], masteryStatus: changes.masteryStatus || safe.masteryStatus }); }
