import exerciseAsset from "../../curriculum/lessons/L-04-01/exercise.json" with { type: "json" };
import scenarioBank from "../../curriculum/lessons/L-04-01/scenario_bank.json" with { type: "json" };
import answerKey from "../../curriculum/lessons/L-04-01/answer_key.json" with { type: "json" };

export const textAnalysisExercise = exerciseAsset;
export const textAnalysisPrimaryScenarios = scenarioBank.forms.primary;
export const textAnalysisTransferScenarios = scenarioBank.forms.transfer;
export const textAnalysisDimensions = exerciseAsset.dimensions;
export const textAnalysisExplanationDimensions = ["requested_output", "capability", "document_id", "mixed_result"];
const distractors = {
  key_phrase_extraction: { decision: "named_entity_recognition", reason: "topic_determines_capability" }, named_entity_recognition: { decision: "key_phrase_extraction", reason: "important_words_are_always_entities" }, sentiment_analysis: { decision: "summarization", reason: "sentiment_is_a_shorter_version" }, summarization: { decision: "key_phrase_extraction", reason: "a_phrase_list_is_a_coherent_summary" },
  P05: { decision: "drop_document_ids_after_submit", reason: "batch_order_alone_guarantees_attribution" }, P06: { decision: "assume_all_documents_succeeded", reason: "one_error_invalidates_or_replaces_all_results" }, T05: { decision: "use_document_position_only", reason: "positions_always_connect_errors_to_inputs" }, T06: { decision: "read_every_item_as_success", reason: "structured_results_never_mix_errors_and_successes" },
};
const tags = { key_phrase_extraction: "keywords-are-entities", named_entity_recognition: "keywords-are-entities", sentiment_analysis: "sentiment-is-summary", summarization: "summary-is-key-phrases", P05: "drops-document-id", T05: "drops-document-id", P06: "ignores-per-document-errors", T06: "ignores-per-document-errors" };
const validTags = new Set(exerciseAsset.misconception_tags); const all = [...textAnalysisPrimaryScenarios, ...textAnalysisTransferScenarios];
export function getTextAnalysisOptions(scenarioId, form = scenarioId?.startsWith("T") ? "transfer" : "primary") { const scenario = scenarioBank.forms[form].find((item) => item.id === scenarioId); const expected = answerKey.forms[form][scenarioId]; const wrong = distractors[scenarioId] || distractors[scenario.topic]; return { decision: [expected.decision, wrong.decision], reason: [expected.reason, wrong.reason] }; }
export function evaluateTextAnalysisScenario(scenarioId, response, form = scenarioId?.startsWith("T") ? "transfer" : "primary") { const expected = answerKey.forms[form]?.[scenarioId]; if (!expected) return null; const correctness = Object.fromEntries(textAnalysisDimensions.map((key) => [key, response[key] === expected[key]])); const passed = Object.values(correctness).every(Boolean); const scenario = scenarioBank.forms[form].find((item) => item.id === scenarioId); return { correctness, score: Object.values(correctness).filter(Boolean).length, passed, misconceptionTags: passed ? [] : [tags[scenarioId] || tags[scenario.topic]] }; }
function normalize(value) { return String(value ?? "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""); }
export function evaluateTextAnalysisExplanation(response) { const expected = { requested_output: "important_phrases_representing_main_concepts", capability: "key_phrase_extraction_keyword_extraction_bridge", document_id: "stable_id_correlates_each_input_result_or_error", mixed_result: "iterate_each_document_and_branch_success_or_error" }; const correctness = Object.fromEntries(textAnalysisExplanationDimensions.map((key) => [key, normalize(response[key]) === expected[key]])); return { correctness, score: Object.values(correctness).filter(Boolean).length, passed: Object.values(correctness).every(Boolean) }; }
export function textAnalysisRemediation(scenario, result, level) { const missed = textAnalysisDimensions.filter((key) => !result.correctness[key]); if (level <= 1) return `Review ${missed.join(" and ")}: name the requested output, not the topic.`; if (level === 2) return `Contrast the nearest capability for this ${scenario.topic.replaceAll("_", " ")} item.`; return "Preserve the document ID and branch per document because one batch can mix results and errors."; }
export function getTextAnalysisFeedback(scenario, result, level) {
  if (!result) return { systemScore: "Awaiting both workload dimensions.", teacherRemediation: null };
  return { systemScore: `${result.score}/2 · ${result.passed ? "CHOICE PASS · both dimensions confirmed." : "CHOICE NOT YET COMPLETE."}`, teacherRemediation: result.passed ? null : textAnalysisRemediation(scenario, result, level) };
}
export function getTextAnalysisExplanationFeedback(result) {
  if (!result) return { systemScore: "Awaiting the learner's four-part explanation.", teacherRemediation: null };
  return { systemScore: `${result.score}/4 · ${result.passed ? "EXPLANATION PASS · all four dimensions confirmed." : "EXPLANATION NOT YET COMPLETE."}`, teacherRemediation: result.passed ? null : "Name the requested output, terminology bridge, stable document ID, and per-document success/error branch." };
}
function formComplete(c, scenarios) { return scenarios.every((scenario) => textAnalysisDimensions.every((key) => c[scenario.id]?.[key] === true)); }
export function sanitizeTextAnalysisEvidence(value) { if (!value || typeof value !== "object" || value.exerciseId !== exerciseAsset.exercise_id) return null; const dimensionCorrectness = {}; for (const scenario of [...all, { id: "explanation", dimensions: textAnalysisExplanationDimensions }]) { const keys = scenario.dimensions || textAnalysisDimensions; if (value.dimensionCorrectness?.[scenario.id]) dimensionCorrectness[scenario.id] = Object.fromEntries(keys.filter((key) => typeof value.dimensionCorrectness[scenario.id][key] === "boolean").map((key) => [key, value.dimensionCorrectness[scenario.id][key]])); } const strict = formComplete(dimensionCorrectness, textAnalysisPrimaryScenarios) && formComplete(dimensionCorrectness, textAnalysisTransferScenarios) && textAnalysisExplanationDimensions.every((key) => dimensionCorrectness.explanation?.[key] === true); let masteryStatus = ["in_progress", "remediation_required", "primary_complete", "transfer_complete", "mastered"].includes(value.masteryStatus) ? value.masteryStatus : "in_progress"; if (masteryStatus === "mastered" && !strict) masteryStatus = formComplete(dimensionCorrectness, textAnalysisTransferScenarios) ? "transfer_complete" : formComplete(dimensionCorrectness, textAnalysisPrimaryScenarios) ? "primary_complete" : "in_progress"; return { exerciseId: exerciseAsset.exercise_id, lessonId: exerciseAsset.lesson_id, activityId: exerciseAsset.activity_id, assessmentIds: [...exerciseAsset.assessment_ids], objectiveIds: [...exerciseAsset.objective_ids], skillIds: [...exerciseAsset.skill_ids], form: ["primary", "transfer", "explanation"].includes(value.form) ? value.form : "primary", dimensionCorrectness, attemptCount: Math.min(99, Math.max(0, Number.isInteger(value.attemptCount) ? value.attemptCount : 0)), hintLevel: Math.min(3, Math.max(0, Number.isInteger(value.hintLevel) ? value.hintLevel : 0)), confidence: ["low", "medium", "high"].includes(value.confidence) ? value.confidence : null, misconceptionTags: Array.isArray(value.misconceptionTags) ? [...new Set(value.misconceptionTags.filter((tag) => validTags.has(tag)))] : [], masteryStatus }; }
export function updateTextAnalysisEvidence(previous, changes = {}) { const safe = sanitizeTextAnalysisEvidence(previous) || sanitizeTextAnalysisEvidence({ exerciseId: exerciseAsset.exercise_id }); const dimensionCorrectness = { ...safe.dimensionCorrectness }; if (changes.scenarioId && changes.correctness) dimensionCorrectness[changes.scenarioId] = changes.correctness; return sanitizeTextAnalysisEvidence({ ...safe, form: changes.form || safe.form, dimensionCorrectness, attemptCount: safe.attemptCount + (changes.incrementAttempt ? 1 : 0), hintLevel: Math.max(safe.hintLevel, changes.hintLevel || 0), confidence: changes.confidence || safe.confidence, misconceptionTags: changes.clearMisconceptionTags ? [] : [...safe.misconceptionTags, ...(changes.misconceptionTags || [])], masteryStatus: changes.masteryStatus || safe.masteryStatus }); }
