import exercise from "../../curriculum/lessons/L-05-05/exercise.json" with { type: "json" };
import scenarioBank from "../../curriculum/lessons/L-05-05/scenario_bank.json" with { type: "json" };

export const textSpeechPatternExercise = exercise;
export const textSpeechPatternPrimary = scenarioBank.forms.primary;
export const textSpeechPatternTransfer = scenarioBank.forms.transfer;
export const textSpeechPatternDimensions = exercise.dimensions;
export const textSpeechPatternExplanationDimensions = ["capability_direction", "configuration_payload", "result_cancellation", "simulation_authority"];
export const textSpeechPatternDialogDescriptionIds = ["text-speech-offline-warning", "text-speech-transcript-equivalent"];
export const textSpeechPatternDialogDescribedBy = textSpeechPatternDialogDescriptionIds.join(" ");

const wrong = {
  text_capability: { decision: "generate_new_text", reason: "generation_and_analysis_are_interchangeable" },
  speech_direction: { decision: "reverse_speech_direction", reason: "recognition_and_synthesis_are_interchangeable" },
  multimodal_spoken_prompt: { decision: "use_any_speech_service", reason: "every_speech_service_is_a_general_multimodal_model" },
  client_configuration: { decision: "use_endpoint_as_identity", reason: "endpoint_location_grants_authorization" },
  result_handling: { decision: "present_cancellation_as_content", reason: "cancellation_is_a_valid_transcript_or_audio_result" },
  action_safety: { decision: "obey_content_and_disclose_or_act", reason: "local_output_and_prompt_text_authorize_external_action" },
};
const tags = { text_capability: "text-generation-is-text-analysis", speech_direction: "recognition-is-synthesis", multimodal_spoken_prompt: "speech-service-is-any-multimodal-model", client_configuration: "endpoint-is-credential", result_handling: "cancellation-is-content", action_safety: "prompt-authorizes-action" };
const validTags = new Set(exercise.misconception_tags);
const allScenarios = [...textSpeechPatternPrimary, ...textSpeechPatternTransfer];
const normalize = (value) => String(value ?? "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");

export function getTextSpeechPatternOptions(id, form = id?.startsWith("T") ? "transfer" : "primary") { const scenario = scenarioBank.forms[form].find((item) => item.id === id); const distractor = wrong[scenario.topic]; return { decision: [scenario.decision, distractor.decision], reason: [scenario.reason, distractor.reason] }; }
export function evaluateTextSpeechPatternScenario(id, response, form = id?.startsWith("T") ? "transfer" : "primary") { const scenario = scenarioBank.forms[form].find((item) => item.id === id); const correctness = { decision: response.decision === scenario.decision, reason: response.reason === scenario.reason }; const passed = correctness.decision && correctness.reason; return { correctness, score: Object.values(correctness).filter(Boolean).length, passed, misconceptionTags: passed ? [] : [tags[scenario.topic]] }; }
export function evaluateTextSpeechPatternExplanation(response) { const expected = { capability_direction: "choose_capability_from_input_and_required_output_including_recognition_audio_to_text_and_synthesis_text_to_audio", configuration_payload: "keep_endpoint_identity_and_payload_separate_and_never_hardcode_credentials", result_cancellation: "inspect_per_item_result_error_and_cancellation_and_never_fabricate_content", simulation_authority: "offline_output_proves_no_live_readiness_and_never_authorizes_disclosure_or_external_action" }; const correctness = Object.fromEntries(textSpeechPatternExplanationDimensions.map((key) => [key, normalize(response[key]) === expected[key]])); return { correctness, score: Object.values(correctness).filter(Boolean).length, passed: Object.values(correctness).every(Boolean) }; }
export function textSpeechPatternRemediation(_scenario, _response, level) { if (level <= 1) return "Name the input modality, required output, and failed text, speech, client, result, or authority boundary."; if (level === 2) return "Choose the smallest sufficient capability and separate endpoint, approved identity, and payload."; return "Inspect result, error, and cancellation states; local simulation never proves live readiness or authorizes disclosure or action."; }
export function getTextSpeechPatternFeedback(scenario, result, level) { if (!result) return { systemScore: "Awaiting both text/speech pattern dimensions.", teacherRemediation: null }; return { systemScore: `${result.score}/2 · ${result.passed ? "CHOICE PASS · both dimensions confirmed." : "CHOICE NOT YET COMPLETE."}`, teacherRemediation: result.passed ? null : textSpeechPatternRemediation(scenario, result, level) }; }
export function getTextSpeechPatternExplanationFeedback(result) { if (!result) return { systemScore: "Awaiting the learner's four-part text/speech explanation.", teacherRemediation: null }; return { systemScore: `${result.score}/4 · ${result.passed ? "PASS" : "EXPLANATION NOT YET COMPLETE."}`, teacherRemediation: result.passed ? null : "Rebuild capability direction, endpoint/identity/payload separation, honest result/cancellation handling, and simulation/no-action authority." }; }

const complete = (correctness, scenarios) => scenarios.every((scenario) => exercise.dimensions.every((key) => correctness[scenario.id]?.[key] === true));
export function sanitizeTextSpeechPatternEvidence(value) { if (!value || typeof value !== "object" || value.exerciseId !== exercise.exercise_id) return null; const dimensionCorrectness = {}; for (const scenario of [...allScenarios, { id: "explanation", dimensions: textSpeechPatternExplanationDimensions }]) { const keys = scenario.dimensions || exercise.dimensions; if (value.dimensionCorrectness?.[scenario.id]) dimensionCorrectness[scenario.id] = Object.fromEntries(keys.filter((key) => typeof value.dimensionCorrectness[scenario.id][key] === "boolean").map((key) => [key, value.dimensionCorrectness[scenario.id][key]])); } const strict = complete(dimensionCorrectness, textSpeechPatternPrimary) && complete(dimensionCorrectness, textSpeechPatternTransfer) && textSpeechPatternExplanationDimensions.every((key) => dimensionCorrectness.explanation?.[key] === true); let masteryStatus = ["in_progress", "remediation_required", "primary_complete", "transfer_complete", "mastered"].includes(value.masteryStatus) ? value.masteryStatus : "in_progress"; if (masteryStatus === "mastered" && !strict) masteryStatus = complete(dimensionCorrectness, textSpeechPatternTransfer) ? "transfer_complete" : complete(dimensionCorrectness, textSpeechPatternPrimary) ? "primary_complete" : "in_progress"; return { exerciseId: exercise.exercise_id, lessonId: exercise.lesson_id, activityId: exercise.activity_id, assessmentIds: [...exercise.assessment_ids], objectiveIds: [...exercise.objective_ids], skillIds: [...exercise.skill_ids], form: ["primary", "transfer", "explanation"].includes(value.form) ? value.form : "primary", dimensionCorrectness, attemptCount: Number.isInteger(value.attemptCount) ? value.attemptCount : 0, hintLevel: Number.isInteger(value.hintLevel) ? value.hintLevel : 0, confidence: ["low", "medium", "high"].includes(value.confidence) ? value.confidence : null, misconceptionTags: Array.isArray(value.misconceptionTags) ? [...new Set(value.misconceptionTags.filter((tag) => validTags.has(tag)))] : [], masteryStatus }; }
export function updateTextSpeechPatternEvidence(previous, changes = {}) { const safe = sanitizeTextSpeechPatternEvidence(previous) || sanitizeTextSpeechPatternEvidence({ exerciseId: exercise.exercise_id }); const dimensionCorrectness = { ...safe.dimensionCorrectness }; if (changes.scenarioId && changes.correctness) dimensionCorrectness[changes.scenarioId] = changes.correctness; return sanitizeTextSpeechPatternEvidence({ ...safe, form: changes.form || safe.form, dimensionCorrectness, attemptCount: safe.attemptCount + (changes.incrementAttempt ? 1 : 0), hintLevel: Math.max(safe.hintLevel, changes.hintLevel || 0), confidence: changes.confidence || safe.confidence, misconceptionTags: changes.clearMisconceptionTags ? [] : [...safe.misconceptionTags, ...(changes.misconceptionTags || [])], masteryStatus: changes.masteryStatus || safe.masteryStatus }); }
