import { FIRST_RUN_RESPONSIVE_LAYOUTS } from "./responsiveImageProjection.js";
export const THREE_THROAT_REPLICA_BLOOM_COPY = Object.freeze({ alt: "Three different alien currents enter one capped return beside three sealed material-keyed replicas on a dry outer foundation." });
const source = Object.freeze({ enabled: true, path: "Visual Direction/Production Masters/2026-08-14-first-run-host23/host23-environment-master-v1.png", sourceId: "HA-IMG-H23-v1", bytes: 3765522, sha256: "7471fba271e4722eebf4d6d951bd96d578adaf3a368a10d670da3a031cfe41eb", width: 1920, height: 1080, format: "png", color: "opaque-srgb-8" });
const provenance = Object.freeze({ schema: "horizon.image-toolkit.production-master.v1", path: source.path, sourceId: source.sourceId, bytes: source.bytes, sha256: source.sha256 });
export const THREE_THROAT_REPLICA_BLOOM_REGISTRY = Object.freeze({ schema: "horizon.three-throat-replica-bloom.v1", source, provenance, layouts: Object.freeze(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: THREE_THROAT_REPLICA_BLOOM_COPY });
export function auditThreeThroatReplicaBloom(registry = THREE_THROAT_REPLICA_BLOOM_REGISTRY) { const candidate = registry?.source; return Object.freeze({ source: candidate?.enabled === true && Object.keys(source).every((key) => candidate[key] === source[key]), provenance: provenance.schema === registry?.provenance?.schema && ["path", "sourceId", "bytes", "sha256"].every((key) => registry.provenance[key] === candidate?.[key]), layouts: JSON.stringify(registry?.layouts) === JSON.stringify(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: registry?.copy === THREE_THROAT_REPLICA_BLOOM_COPY }); }
export function deriveThreeThroatReplicaBloomState({ registry = THREE_THROAT_REPLICA_BLOOM_REGISTRY, decodedImage } = {}) { return Object.values(auditThreeThroatReplicaBloom(registry)).every(Boolean) && decodedImage?.complete === true && decodedImage.naturalWidth === 1920 && decodedImage.naturalHeight === 1080 ? "available" : "hidden"; }
export const CAPPED_RETURN_PRISM_COPY = Object.freeze({ alt: "A thick outer-service prism refracts the geometry of three distinct currents entering an opaque capped return, beside a dry outbound carrier margin." });
const prismSource = Object.freeze({ enabled: true, path: "Visual Direction/Production Masters/2026-08-14-first-run-host24/host24-environment-master-v1.png", sourceId: "HA-IMG-H24-v1", bytes: 3849344, sha256: "f64c81f870f507b6ef10eec41aae51a7d27d02481176f8a70f1087d66947b439", width: 1920, height: 1080, format: "png", color: "opaque-srgb-8" });
const prismProvenance = Object.freeze({ schema: provenance.schema, path: prismSource.path, sourceId: prismSource.sourceId, bytes: prismSource.bytes, sha256: prismSource.sha256 });
export const CAPPED_RETURN_PRISM_REGISTRY = Object.freeze({ schema: "horizon.capped-return-prism.v1", source: prismSource, provenance: prismProvenance, layouts: Object.freeze(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: CAPPED_RETURN_PRISM_COPY });
export function auditCappedReturnPrism(registry = CAPPED_RETURN_PRISM_REGISTRY) { const candidate = registry?.source; return Object.freeze({ source: candidate?.enabled === true && Object.keys(prismSource).every((key) => candidate[key] === prismSource[key]), provenance: prismProvenance.schema === registry?.provenance?.schema && ["path", "sourceId", "bytes", "sha256"].every((key) => registry.provenance[key] === candidate?.[key]), layouts: JSON.stringify(registry?.layouts) === JSON.stringify(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: registry?.copy === CAPPED_RETURN_PRISM_COPY }); }
export function deriveCappedReturnPrismState({ registry = CAPPED_RETURN_PRISM_REGISTRY, decodedImage } = {}) { return Object.values(auditCappedReturnPrism(registry)).every(Boolean) && decodedImage?.complete === true && decodedImage.naturalWidth === 1920 && decodedImage.naturalHeight === 1080 ? "available" : "hidden"; }
