import { FIRST_RUN_RESPONSIVE_LAYOUTS } from "./responsiveImageProjection.js";
export const MEMBRANE_FOAM_SEAM_COPY = Object.freeze({ alt: "A dark conductive seam persists from a pressure-bent translucent membrane into porous mineral foam beside a stable ceramic anchor-line approach." });
export const RADIAL_SAMPLE_SLEEVES_COPY = Object.freeze({ alt: "Radial mineral sample sleeves terminate locally on a maintained bypass beside a dense opaque alien margin that remains closed and unavailable." });
const source = Object.freeze({ enabled: true, path: "Visual Direction/Production Masters/2026-08-14-first-run-host37/host37-environment-master-v1.png", sourceId: "HA-IMG-H37-v1", bytes: 3445772, sha256: "41c354718d21767cf7336ab650d52337027ce40a5bc0e5018c522ae001a27cb8", width: 1920, height: 1080, format: "png", color: "opaque-srgb-8" });
const provenance = Object.freeze({ schema: "horizon.image-toolkit.production-master.v1", path: source.path, sourceId: source.sourceId, bytes: source.bytes, sha256: source.sha256 });
export const MEMBRANE_FOAM_SEAM_REGISTRY = Object.freeze({ schema: "horizon.membrane-foam-seam.v1", source, provenance, layouts: Object.freeze(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: MEMBRANE_FOAM_SEAM_COPY });
const source38 = Object.freeze({ enabled: true, path: "Visual Direction/Production Masters/2026-08-14-first-run-host38/host38-environment-master-v1.png", sourceId: "HA-IMG-H38-v1", bytes: 4200442, sha256: "f2b114c7fe5ec081a6d2c39933b9aed7a32898e61dc8c8edf6908599c098c666", width: 1920, height: 1080, format: "png", color: "opaque-srgb-8" });
const provenance38 = Object.freeze({ schema: "horizon.image-toolkit.production-master.v1", path: source38.path, sourceId: source38.sourceId, bytes: source38.bytes, sha256: source38.sha256 });
export const RADIAL_SAMPLE_SLEEVES_REGISTRY = Object.freeze({ schema: "horizon.radial-sample-sleeves.v1", source: source38, provenance: provenance38, layouts: Object.freeze(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: RADIAL_SAMPLE_SLEEVES_COPY });
export function auditMembraneFoamSeam(registry = MEMBRANE_FOAM_SEAM_REGISTRY) { const candidate = registry?.source; return Object.freeze({ source: candidate?.enabled === true && Object.keys(source).every((key) => candidate[key] === source[key]), provenance: provenance.schema === registry?.provenance?.schema && ["path", "sourceId", "bytes", "sha256"].every((key) => registry.provenance[key] === candidate?.[key]), layouts: JSON.stringify(registry?.layouts) === JSON.stringify(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: registry?.copy === MEMBRANE_FOAM_SEAM_COPY }); }
export function deriveMembraneFoamSeamState({ registry = MEMBRANE_FOAM_SEAM_REGISTRY, decodedImage } = {}) { return Object.values(auditMembraneFoamSeam(registry)).every(Boolean) && decodedImage?.complete === true && decodedImage.naturalWidth === 1920 && decodedImage.naturalHeight === 1080 ? "available" : "hidden"; }
export function auditRadialSampleSleeves(registry = RADIAL_SAMPLE_SLEEVES_REGISTRY) { const candidate = registry?.source; return Object.freeze({ source: candidate?.enabled === true && Object.keys(source38).every((key) => candidate[key] === source38[key]), provenance: provenance38.schema === registry?.provenance?.schema && ["path", "sourceId", "bytes", "sha256"].every((key) => registry.provenance[key] === candidate?.[key]), layouts: JSON.stringify(registry?.layouts) === JSON.stringify(Object.keys(FIRST_RUN_RESPONSIVE_LAYOUTS)), copy: registry?.copy === RADIAL_SAMPLE_SLEEVES_COPY }); }
export function deriveRadialSampleSleevesState({ registry = RADIAL_SAMPLE_SLEEVES_REGISTRY, decodedImage } = {}) { return Object.values(auditRadialSampleSleeves(registry)).every(Boolean) && decodedImage?.complete === true && decodedImage.naturalWidth === 1920 && decodedImage.naturalHeight === 1080 ? "available" : "hidden"; }
