import exercise from "../../curriculum/lessons/L-05-06/exercise.json" with { type: "json" };
import bank from "../../curriculum/lessons/L-05-06/scenario_bank.json" with { type: "json" };
export const visualPatternExercise=exercise,visualPatternPrimary=bank.forms.primary,visualPatternTransfer=bank.forms.transfer,visualPatternDimensions=exercise.dimensions,visualPatternExplanationDimensions=["capability_media","request_validation","result_provenance","simulation_authority"];
export const visualPatternDialogDescribedBy="visual-pattern-offline-warning visual-pattern-text-equivalent";
const wrong={image_analysis:{decision:"generate_new_image",reason:"analysis_and_generation_are_interchangeable"},multimodal_prompt:{decision:"vision_only_without_question",reason:"multimodal_means_image_without_text_context"},image_generation:{decision:"analyze_existing_image",reason:"analysis_produces_new_visual_media"},request_contract:{decision:"trust_file_extension",reason:"extension_alone_proves_supported_media"},result_provenance:{decision:"treat_every_result_as_observed_media",reason:"generated_media_is_ground_truth_without_provenance"},action_safety:{decision:"publish_or_delete_as_prompted",reason:"local_output_authorizes_publication_or_deletion"}},tags={image_analysis:"analysis-is-generation",multimodal_prompt:"multimodal-is-vision-only",image_generation:"generation-is-analysis",request_contract:"extension-proves-media-valid",result_provenance:"generated-media-is-ground-truth",action_safety:"prompt-authorizes-publication"},valid=new Set(exercise.misconception_tags),all=[...visualPatternPrimary,...visualPatternTransfer],norm=v=>String(v??"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
export function getVisualPatternOptions(id,form=id?.startsWith("T")?"transfer":"primary"){const s=bank.forms[form].find(x=>x.id===id),w=wrong[s.topic];return{decision:[s.decision,w.decision],reason:[s.reason,w.reason]};}
export function evaluateVisualPatternScenario(id,response,form=id?.startsWith("T")?"transfer":"primary"){const s=bank.forms[form].find(x=>x.id===id),correctness={decision:response.decision===s.decision,reason:response.reason===s.reason},passed=correctness.decision&&correctness.reason;return{correctness,score:Object.values(correctness).filter(Boolean).length,passed,misconceptionTags:passed?[]:[tags[s.topic]]};}
export function evaluateVisualPatternExplanation(response){const expected={capability_media:"choose_analysis_for_existing_pixels_multimodal_for_image_plus_text_and_generation_for_new_media",request_validation:"validate_media_bytes_type_request_and_deployed_capability_before_processing",result_provenance:"parse_operation_specific_result_shape_and_label_generated_content_with_source_model_prompt_and_time",simulation_authority:"offline_output_proves_no_live_readiness_and_never_authorizes_publication_or_deletion"},correctness=Object.fromEntries(visualPatternExplanationDimensions.map(k=>[k,norm(response[k])===expected[k]]));return{correctness,score:Object.values(correctness).filter(Boolean).length,passed:Object.values(correctness).every(Boolean)};}
export function visualPatternRemediation(_s,_r,l){if(l<=1)return"Name whether media is existing or new, the required output, and the failed capability, request, provenance, or authority boundary.";if(l===2)return"Select the supported deployed capability and validate bytes, media type, and request contract.";return"Parse the operation-specific result, preserve generated-content provenance, and require separate authority for publication or deletion.";}
export function getVisualPatternFeedback(s,r,l){if(!r)return{systemScore:"Awaiting both visual-pattern dimensions.",teacherRemediation:null};return{systemScore:`${r.score}/2 · ${r.passed?"CHOICE PASS · both dimensions confirmed.":"CHOICE NOT YET COMPLETE."}`,teacherRemediation:r.passed?null:visualPatternRemediation(s,r,l)};}
export function getVisualPatternExplanationFeedback(r){if(!r)return{systemScore:"Awaiting the learner's four-part visual-pattern explanation.",teacherRemediation:null};return{systemScore:`${r.score}/4 · ${r.passed?"PASS":"EXPLANATION NOT YET COMPLETE."}`,teacherRemediation:r.passed?null:"Rebuild capability/media selection, request validation, honest operation/result handling with provenance, and simulation/no-publication/no-deletion/no-action authority."};}
const complete=(c,ss)=>ss.every(s=>exercise.dimensions.every(k=>c[s.id]?.[k]===true));
export function sanitizeVisualPatternEvidence(v){if(!v||typeof v!=="object"||v.exerciseId!==exercise.exercise_id)return null;const dimensionCorrectness={};for(const s of[...all,{id:"explanation",dimensions:visualPatternExplanationDimensions}]){const ks=s.dimensions||exercise.dimensions;if(v.dimensionCorrectness?.[s.id])dimensionCorrectness[s.id]=Object.fromEntries(ks.filter(k=>typeof v.dimensionCorrectness[s.id][k]==="boolean").map(k=>[k,v.dimensionCorrectness[s.id][k]]));}const strict=complete(dimensionCorrectness,visualPatternPrimary)&&complete(dimensionCorrectness,visualPatternTransfer)&&visualPatternExplanationDimensions.every(k=>dimensionCorrectness.explanation?.[k]===true);let masteryStatus=["in_progress","remediation_required","primary_complete","transfer_complete","mastered"].includes(v.masteryStatus)?v.masteryStatus:"in_progress";if(masteryStatus==="mastered"&&!strict)masteryStatus=complete(dimensionCorrectness,visualPatternTransfer)?"transfer_complete":complete(dimensionCorrectness,visualPatternPrimary)?"primary_complete":"in_progress";return{exerciseId:exercise.exercise_id,lessonId:exercise.lesson_id,activityId:exercise.activity_id,assessmentIds:[...exercise.assessment_ids],objectiveIds:[...exercise.objective_ids],skillIds:[...exercise.skill_ids],form:["primary","transfer","explanation"].includes(v.form)?v.form:"primary",dimensionCorrectness,attemptCount:Number.isInteger(v.attemptCount)?v.attemptCount:0,hintLevel:Number.isInteger(v.hintLevel)?v.hintLevel:0,confidence:["low","medium","high"].includes(v.confidence)?v.confidence:null,misconceptionTags:Array.isArray(v.misconceptionTags)?[...new Set(v.misconceptionTags.filter(t=>valid.has(t)))]:[],masteryStatus};}
export function updateVisualPatternEvidence(p,c={}){const s=sanitizeVisualPatternEvidence(p)||sanitizeVisualPatternEvidence({exerciseId:exercise.exercise_id}),d={...s.dimensionCorrectness};if(c.scenarioId&&c.correctness)d[c.scenarioId]=c.correctness;return sanitizeVisualPatternEvidence({...s,form:c.form||s.form,dimensionCorrectness:d,attemptCount:s.attemptCount+(c.incrementAttempt?1:0),hintLevel:Math.max(s.hintLevel,c.hintLevel||0),confidence:c.confidence||s.confidence,misconceptionTags:c.clearMisconceptionTags?[]:[...s.misconceptionTags,...(c.misconceptionTags||[])],masteryStatus:c.masteryStatus||s.masteryStatus});}
